---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdaemon
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: appdaemon
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/tallmega/appdaemon-dependencies
      tag: v1
      pullPolicy: Always

    env:
      TZ: America/Toronto
      HA_URL: http://10.10.10.203:8123
      DASH_URL: http://0.0.0.0:5050

    envFrom:
    - secretRef:
       name: appdaemon-secret
        service:
      main:
        ports:
          http:
            port: 5050
    ingress:
      main:
        enabled: false
    # -- Enable devices to be discoverable
    # hostNetwork: true

    # -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
    # dnsPolicy: ClusterFirstWithHostNet

    #securityContext:
    # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
    # privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: appdaemonconfig-pvc
      # -- Configure a hostPathMount to mount a USB device in the container.