apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appdaemon-secret
  namespace: default
spec:
  encryptedData:
    TOKEN: AgAqSaJFONtDX75QGctYVg7QC2R/T3/i/PiZhAQ8wYxssT6V+OPfskPPQmVgXV0GVUXCrvZkWW7uI4ArFy/gcrWfBXKTPCS18Psvox7xzFy4BLgLci0y4DkfztDhi1r5Cd92O7JyABv8oyCLqffnTUvv2S5t1S/vpA8TIVM5/YHKq5oz3lqOJP7ZLsftF+lSdpMn23zfPbHInltYS80fDpMiAIIdA4DkBABhMlb7TrSXvgTAWi3IODtMX2sMtP5SHQFmCJj7Hzn/IpDZ+uH1PtNj+Ti8S4B7zzHtEj1pHOC96Qh5f/KRUYyRCtozP2w7uhEQbGNnqY+QBolx8UVe6jiB+7VcKNvdNqBV/KzonsrJ48kuDVpe6FNh5AYyG6GhT2DZ8mAAhaO7tKLZiDsiqDOvLpDqyUq2MZ9H2rWAjOVMolDRVqG7IZqLzRQ8jWowixFApmIwV10U29cDkahTZKcsjdVu8gk+HQ9HCk/O9cL2KrafDVUtKGbD0m99GVLttgatHiRGYZX3gfbWJCZSyT8xsRj7qBX2GrkAIIKOQt5toPCFCUGqNUC/tLZW0l4Yx4VfDNxnsVFxspIMmEnf9zaFNWZrFixFx/rx3zSACojSduOuSVscP4tyTy1J/QWMvMo4mdJ2ZHxMDS41rbyGVJCKqzADLalA1By22r7CLIEp0/0SOqyTbtFVH5Sa+HVDI4hkSMkZUfIuuz4ogMGHDLb6jw7h34H7z5jC9grsNsFjzHBjQuLn/BUddXq1E9SpUsZfubIjeHiyFXzgZ6pojqoQpYxqyx+W14KM5kaqUON4Vgr/Ttz2GQWEpToNE6lf5W+dLYUqq5hy6XmlYGODXP9ZLfHy8X1JvILuXqOQ+e9ekvrH7uMv25hl1tiX9iqBdVmLUqc5KeQJ1P4261N9U1NKh/eEKg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: appdaemon-secret
      namespace: default