---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdaemon
  namespace: default
spec:
  interval: 5m
  chart:
     spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: appdaemon
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: acockburn/appdaemon
      tag: 4.0.8
      pullPolicy: IfNotPresent
    #command: ['sh', '-c', 'apk add --update --no-cache g++ gcc libxslt-dev && pip install lxml && pip install numpy']
    env:
      TZ: America/Toronto
      HA_URL: http://10.10.10.203:8123
      DASH_URL: http://10.10.10.200:5050
    envFrom:
    - secretRef:
       name: appdaemon-secret
    
    probes:
    # -- Liveness probe configuration
    # @default -- See below
      liveness:
        # -- Enable the liveness probe
        enabled: true
        # -- Set this to `true` if you wish to specify your own livenessProbe
        custom: true
        # -- The spec field contains the values for the default livenessProbe.
        # If you selected `custom: true`, this field holds the definition of the livenessProbe.
        # @default -- See below
        spec:
          initialDelaySeconds: 1200
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

      # -- Redainess probe configuration
      # @default -- See below
      readiness:
        # -- Enable the readiness probe
        enabled: true
        # -- Set this to `true` if you wish to specify your own readinessProbe
        custom: true
        # -- The spec field contains the values for the default readinessProbe.
        # If you selected `custom: true`, this field holds the definition of the readinessProbe.
        # @default -- See below
        spec:
          initialDelaySeconds: 1200
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

      # -- Startup probe configuration
      # @default -- See below
      startup:
        # -- Enable the startup probe
        enabled: true
        # -- Set this to `true` if you wish to specify your own startupProbe
        custom: true
        # -- The spec field contains the values for the default startupProbe.
        # If you selected `custom: true`, this field holds the definition of the startupProbe.
        # @default -- See below
        spec:
          initialDelaySeconds: 1200
          timeoutSeconds: 1
          ## This means it has a maximum of 5*30=150 seconds to start up before it fails
          periodSeconds: 5
          failureThreshold: 30

    service:
      main:
        ports:
          http:
            port: 5050      
    ingress:
      main:
        enabled: false

# -- Enable devices to be discoverable
# hostNetwork: true

# -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
# dnsPolicy: ClusterFirstWithHostNet

#securityContext:
# -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
  # privileged: true

    persistence:
      config:
        enabled: true
        existingClaim: appdaemonconfig-pvc
      # -- Configure a hostPathMount to mount a USB device in the container.

    