apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appdaemon-secret
  namespace: default
spec:
  encryptedData:
    TOKEN: AgBHx/LXendefrTRiOPP7Gs/M7droTwNkJ0qoQRTvydDADxODltSe+5L/ZPgt2Zf/FKhqWcEjIK43GRhnsbz1l2VpRF3LS6vjDsejRpZ4V57G5ET3seOWqKCqFyiKrUVRMZfV4SlKEujEynDytiHyfN9OL/pu4EiAD0VwIt2J+phfJu4O+/jmp78MESbr146J8ZnpFDLxqKahGiQGdQiPn2p9vVMR9Qq9uxD26/FlVMSAJ7W+bkdp9jZ5gCMyxd+7WCzXSdHSMp3KSb1NlyY2ewwOlFMRjV+vZ0zWW9A/m1I+F0hA2p5zOoXHFtLXHWeAgLa06un4qe3c3imBTzJGS9ClqLdxS44HD4ljVkXzKaZqhY7vG/sV1qkrcddOsPWYXdZbLuK5tc84S61/zkTbq4/RF0GZFAHjtlJ/RQi/RvtX1rLZ48KXeA7S7OdmLSIb7j4jx/zCNY+hLfAh7PvFmjYyaAHqZz28qmZprW13HgdqZuGWGJt6Y+T1ElAu+cB/bUpzf1ea8gPtxTNrhdYfOcSDNs5o5m/b18/XcK+rdgcrwyMtVSu8bMLqkIoYAOKFEcWRvWiORWIsKy2kCO/xdy0BnKYOVE4+XbTqk4qJrkDV4CPi10WOZA3UWXE2QHB44ih++ru1DYMiS4TQaz71WpZurGxvcOgcEt0BdHLsXblV6IxAL4wH9Z+QThRzjgp6Fhah5GPfi0RyI6DRFQznYypzZr/1fwkgTMP1dW9o2dAlCjsvkCdE43kswl0+g1wNG1l71N94Hg0Y0pxu8eSigh6Z4Y9d6geQ/pYYEe1EfPxJQmf2QyIaTKQgeilmXTM7apaZVa/KY9qSeSRbG6oDgWhxvDn6KDJ6htNp7kwLyiflBwAnhR0UeWJEmgONYbIAYz2yvWlqiWFwkK568nDWgY/ydylN3Q64ACxXMaBizXoTtTRfnPXQ3c=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: appdaemon-secret
      namespace: default