---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdaemonconfig-pvc1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: syno-nfs
  volumeName: appdaemonconfig-pv1
