apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sonarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sonarr
  policy:
    semver:
      range: '>= 3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: calibre-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: calibre-web
  policy:
    semver:
      range: '>= 0.6.21 <1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: mealie
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mealie
  policy:
    semver:
      range: '>= 1.3.2'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: maintainerr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: maintainerr
  policy:
    semver:
      range: '>= 2.0.4'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: calibre
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: calibre
  policy:
    semver:
      range: '>= 7.7.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frigate
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frigate
  policy:
    semver:
      range: '>= 0.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: metube
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: metube
  filterTags:
    pattern: '^(?P<year>0|[0-9]\d*)\-(?P<month>[0-9][0-9])\-(?P<day>0|[0-9]\d*)$'
  policy:
    alphabetical:
      order: asc
---
# Commented out until stable builds are available.
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: readarr
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: readarr
#   policy:
#     semver:
#       range: '>= 7.7.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: radarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radarr
  policy:
    semver:
      range: '>= 3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ombi
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ombi
  policy:
    semver:
      range: '>= 4.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: tautulli
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: tautulli
  policy:
    semver:
      range: '>= 2.13.3 <1000.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sabnzbd
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sabnzbd
  policy:
    semver:
      range: '>= 3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homeassistant
  policy:
    semver:
      range: '>= 2021.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: plex
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: plex
  filterTags:
    pattern: '^(?P<major>0|[0-9]\d*)\.(?P<minor>[0-9][0-9])\.(?P<patch>0|[0-9]\d*)\.(?P<something>0|[0-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: unifi
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: unifi
  policy:
    semver:
      range: '>= 5.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: double-take
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: double-take
  policy:
    semver:
      range: '>= 1.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: eclipse-mosquitto
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: eclipse-mosquitto
  policy:
    semver:
      range: '>= 2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zigbee2mqtt
  policy:
    semver:
      range: '>= 1.26.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: appdaemon
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: appdaemon
  policy:
    semver:
      range: '>= 4.2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wyzebridge
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wyzebridge
  policy:
    semver:
      range: '>= 1.9.0'
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: jellyfin
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: jellyfin
#   policy:
#     semver:
#       range: '>= 8.10.0'