---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appdaemon
  namespace: flux-system
spec:
  interval: 5m
  releaseName: appdaemon
  targetNamespace: default
  chart:
    spec:
      chart: appdaemon
      #version: 8.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: acockburn/appdaemon 
      tag: 4.1.0 # {"$imagepolicy": "flux-system:appdaemon:tag"}
    command: [ "./dockerStart.sh"]
    env:
      TZ: America/Toronto
      HA_URL: http://10.10.10.63:8123
      DASH_URL: http://0.0.0.0:5050

    envFrom:
    - secretRef:
       name: appdaemon-secret
    service:
      main:
        ports:
          http:
            port: 5050
    ingress:
      main:
        enabled: false
    # -- Enable devices to be discoverable
    # hostNetwork: true

    # -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
    # dnsPolicy: ClusterFirstWithHostNet

    #securityContext:
    # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
    # privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: appdaemon-config-pvc
      # -- Configure a hostPathMount to mount a USB device in the container.