apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appdaemon-secret
  namespace: default
spec:
  encryptedData:
    TOKEN: AgAHb9iLtl8LmixIQZvYHbmRPRYGaKVXfKs6g2Q6czXuNTtzDxp+WyWS/8v7wpBumyv0TSNV9jVQw3sZAo23pMfkqBpvjknyHjpfw6BFEHbkI3EUewBVd7xcFzSJtRruAH040IegHIWNEnFuOpZBX3TscaFKzdLTAS3v889LDEPhvG8fbirArgsIxEE3v1uOrQiiVBdb6v2I8T0v4D9kDm7TFw1aClgs68JBy0/rER5L2LkIqskXHZ+ukfuVMGMFKgqNgpU+gGSYNa8yRiukzzC2wL8P0cnSoDHLOKdqjWpj4Eo7mQ/T5nn1RYfbVWRZ/r1gnDyQ9LaB11tt3NqwmzTDm78L1sUuuuCb17apBbqkLxsQRNvsQ3A4auOo5kGotJ9KpRAZDkVqmPv9y7lFDLJ+gxZogiSSmVaTGO/0yRvh2zKjjrUX7JRtZf9yUq0GF/MXEQIh8ONi/ZG9dgfhmt2tbzzY6lgLZWOebt19juMVWpw5muOZYwLjDIfghd7n4l/6r3I7/U8+Dw9ws1tn0vPUfUF76gzuVBOtGjWtnRohagckRi+OU6jnPO5OvmSoNtmLQghnCHyrUxfl22uVDY8Nj8dYoqMAa4VOduwJNtTXyvyYGv5oNA/WymNBLCaBTydDKUK8zRB88CkipB5fagoiyTnhciIVx0gkIAVgYCHbx4JQXiArFK18u84rrOn0mv3NVBAIHnWNoAxkwonqdAyFeNn6tICLrLNKPi+90xjca/vBv6BzHj+tjXfj170gPL8MT+UnzpGix2avI3ySewVg9/Le24Xd6wHpiip76IFM9DhwUvVaxj6WIKVzosf7RYPSlmg+Djyc6lsbdxDVxcZy67s05Vnr3lJKQkJuJzGqtd5M2AudWAEt8tNEsWUSUmtR5BcUN7C58+tsW7z6j44vQ/WYgzuOf7AUA+BOZ3lE0RfgOn7vgHk=
  template:
    metadata:
      creationTimestamp: null
      name: appdaemon-secret
      namespace: default