apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: default
spec:
  chart:
    spec:
      chart: k8s-monitoring
      version: "^1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    cluster:
      name: cluster1
    externalServices:
      prometheus:
        host: https://prometheus-prod-32-prod-ca-east-0.grafana.net
        basicAuth:
          username: "1065506"
          passwordFrom:
            secretKeyRef:
              name: grafana-basic-auth
              key: password
      loki:
        host: https://logs-prod-018.grafana.net
        basicAuth:
          username: "634358"
          passwordFrom:
            secretKeyRef:
              name: grafana-basic-auth
              key: password
      tempo:
        host: https://tempo-prod-13-prod-ca-east-0.grafana.net:443
        basicAuth:
          username: "630862"
          passwordFrom:
            secretKeyRef:
              name: grafana-basic-auth
              key: password
    metrics:
      enabled: true
      alloy:
        metricsTuning:
          useIntegrationAllowList: true
      cost:
        enabled: true
      kepler:
        enabled: true
      node-exporter:
        enabled: true
    logs:
      enabled: true
      pod_logs:
        enabled: true
      cluster_events:
        enabled: true
    traces:
      enabled: true
    receivers:
      grpc:
        enabled: true
      http:
        enabled: true
      zipkin:
        enabled: true
      grafanaCloudMetrics:
        enabled: false
    opencost:
      enabled: true
      opencost:
        exporter:
          defaultClusterId: cluster1
        prometheus:
          external:
            url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    kepler:
      enabled: true
    alloy: {}
    alloy-events: {}
    alloy-logs: {}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgB0r+H8VE/FbeDA7N/llCtufxxMwy5C9ma+YPY3k3jgvGHEFLBaVjVbUa/F1Qp868fYIQgf29rVcNKSTEQ+VfyhTGiTfInTgzgK3zGc275yR45aXSbOgCaUgCCjSvbJNO6YndioT2up1vAZ2kQcATK7g2ln3rQoQ+nbsTRX/zfPuJ+9KwoIxDde45jpGLMRLsprV0RwNxr04SYM9MZZIDPgM1YZUDegJzzpr5a3ufYrSQZJ7+EEfla6nV94qBWBhM79PT32SxRz3D90P5eqpaB0a0N77w/dFVRMUaY8V5kbIcO9SCoNBK8DWyipxvb2fbJlPKsNzmdQNJOXCyLiN2ioq7HHhDuJ//pqmfp8mKCscxC/aj2Zg8P7LdY4WFN7oWUxhodN3KBeTIjrKFGG8B3EzhvIV3DIUiEHkry8sRNTrWXPPF/o6eSMnneGABoNGkuAM8M/h+oG/G8Qm8GADd5WMGQ62U1awXldAQ3ib7i8G0fqabMjJZM3tr+lQV5H1pIg1ilSrQTgia81kcL9EryMWYLhfLvsjkzHu2mZdD7e144o8/HuTlbtFCaZqOPNZhT2pqq0+iur3CCQHjMkEGLMqggrfKVFAy4O1Jd0mx8XKjHXhLHJ3CaH9AF3MLla+HaOCaLXTy5dwQRCque1hWe3Ei/1L/oor3BOc1AQktwZ65KY6TwXaMvHSozrUmEMCb5lJxFZCT7X+PgNEWVGTtKln31itT6yEU+VPhtgEJrSDU0cVX+F9Csk8oEF5GQ+wlFYu/BNxwpOi39YVdpV6aI7vI7Kc2ZseeB1LCIIHdKqqhcjlSMc0CMVaqbbLpxN4svCS1kA879Bg4rayoDUoMIeaJJuI5eo2A/AE4huu/fI6qBzxXIGZs9jSUVbk7yKqsTRHYozXghMjfimo7Eqa1lsQ2P731dVwRw+OIqB4R7Vdjfs7rs7v/V0j8IhRw==