apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: default
spec:
  chart:
    spec:
      chart: k8s-monitoring
      version: "^1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    cluster:
      name: cluster1
    externalServices:
      prometheus:
        host: https://prometheus-prod-32-prod-ca-east-0.grafana.net
        basicAuth:
          username: "1065506"
          passwordFrom:
            secretKeyRef:
              name: grafana-basic-auth
              key: password
      loki:
        host: https://logs-prod-018.grafana.net
        basicAuth:
          username: "634358"
          passwordFrom:
            secretKeyRef:
              name: grafana-basic-auth
              key: password
      tempo:
        host: https://tempo-prod-13-prod-ca-east-0.grafana.net:443
        basicAuth:
          username: "630862"
          passwordFrom:
            secretKeyRef:
              name: grafana-basic-auth
              key: password
    metrics:
      enabled: true
      alloy:
        metricsTuning:
          useIntegrationAllowList: true
      cost:
        enabled: true
      kepler:
        enabled: true
      node-exporter:
        enabled: true
    logs:
      enabled: true
      pod_logs:
        enabled: true
      cluster_events:
        enabled: true
    traces:
      enabled: true
    receivers:
      grpc:
        enabled: true
      http:
        enabled: true
      zipkin:
        enabled: true
      grafanaCloudMetrics:
        enabled: false
    opencost:
      enabled: true
      opencost:
        exporter:
          defaultClusterId: cluster1
        prometheus:
          external:
            url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    kepler:
      enabled: true
    alloy: {}
    alloy-events: {}
    alloy-logs: {}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAWtgBh1c1DKuifabZUbcZsOtTmP2enhPwDDbbBTxTsjQWNf3lck+4qnX7u9hDjLGbE3iS0+tfEny+tJaDZNE1XWmO1cUlD+P/EFuTivpWFFzhQIQlWsY1Vxbpa73VeMmM/NHm9KsJX6u2O5lvT0PQx0/vkgjtmtIDxHGfKuaUAtaGsZX6Kq73IBxR6qGiE9GSbnjO0JSoTKq8ly5quS7UAahMI8u1/2D16xQBUtSf7kN+EA2yAkx/hbVMDF8nVii/oOCRApN5jAcX70c2NpFc9iJWrqGLaI6Su85UgzSjJd0jvMywP4NToaHQ229HIHe/2z0zvsIYb81B+PU/u0gilxY8yM4CYV8M0lAwgeJPevMOeHwnjrSaSVNyWkmaponUzkINfLj62iBJiAbtAMRN/2MKqLKtn2TTVz3DzTZonwl92FBLFzNUwmZei5hZHqnhOjHia3z7NE4em5DHWhE4BCpOAJfk/zEsCdJv2gRQHzn97dSupGlb8tjnNN0RECHd13YruCX2ruhQYm9MzdGHf+NhJumtZ0Yubxj+76I6bqwYiOEo59EyAQEnhzLKP6mvTR+iYW2PiKKj6t8R+fHyoX1Jh+3IFmz8iYE/XLSECV8Aja9lgANfdi3rlFN5yCgrZWbi7PeTZOm0000ITwqBNdAB6I+w6pVRU/vjcCMO780P0tScOkkdGY1MD9sbeTZDAqRW+b1+oPvd4z3/JcQH8JrExBtWwl/ot3HU6eZ1Wvrl9Pm5H/B6Jq062Y3LAgqrMbhrebChjBrsaWnTx+9zSkjqbizkExl2lP0Pd9TCM+lpEJQpe1PCK+Y0LgYMGPEuwovn6DhCcUlxSvlTpFoMvtZpYis/1k6llHUTTu8Uv/dd3y8+6XCDmjEtLSiGfZAiqkLSoaYUjlCc0RkyRnzCJy/f2PZCowYgviPTYGeQymg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-basic-auth
      namespace: default