---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 1h0m0s
  targetNamespace: kube-system
  values:
    bpf:
      hostLegacyRouting: false
    cluster:
      id: 0
      name: kubernetes
    cni:
      customConf: false
      uninstall: false
    encryption:
      nodeEncryption: false
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
        - 10.245.0.0/16
    k8sServiceHost: 10.10.10.50
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    operator:
      replicas: 1
      prometheus:
        enabled: false
      unmanagedPodWatcher:
        restart: true
    policyEnforcementMode: default
    prometheus:
      enabled: false
    hubble:
      # metrics:
      #   enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: false
    serviceAccounts:
      cilium:
        name: cilium
      operator:
        name: cilium-operator
    tunnel: vxlan
    tunnelPort: 8472