---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    managed-by: flux
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    crds: Create
  interval: 10m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    config:
      featureGates:
        ACMEHTTP01IngressPathTypeExact: false