---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: default
spec:
  encryptedData:
    access-key-id: AgBghKN+j0uM1bnp931M82k8Yp06/Jy+O4cgryt7BChAFiSlijNSgOj8PZwkhz6P5o7a/+ilfOSmvZ3vA44//Uc+BI7HDJyYxdA8uwc/toZkLuiTaCjosSlORM7Tew9/NbtEBbjiYNjhUsHMbc/914FniMtQS+d7Ohgvug+SbtmqLrh+3XFQGYVRPL2wBysIj91tniBJEqiMtEohsnvfq/01mROaXsqxJDt/UCE94sYud/UoDnJ1w8NigXVoKBKuMQV1tP7x1z/15aOcrALo0d26nnGFlfljkI6NgayA7I2zJuumiC5AY/YvWrrdhoLlpR5layfyTIS7rZCWhd6WxzjhaP0mF4ZA9uI1zZMT5tArPK5MS6OuaBbPC7P/mOcIpsl/fylCUggjEAvvMlAB//yYUtn8Fe3iUqHgMUl5uGnXw9bg2HLtVmUY/jFLjRx6Oc77FXB6n78kTF75WYPhq5Of16Gzi+9niEKbP3lWXWbJ55KoSF1wWHfhGcAjTLbCDTOE83GrvkOLIXB6/zF4BCfVqSYf27XjY/+wHwmVgIfZzbvwj1FYynH7yT3ykzE3MOaEOGSJFx2GRoVop8hik98qQGx8UCXmVX+Q+oy0poFdMT8mPy1i65yzsK7H3tLzD+Bo8ZSEOsbwp4iD3Bk3WeZXNVgLhu46s67y7S/psoKoem+L/eM3DnCVsnx9hyBBkJnlxpeaBBFLmErwWk9Eg+C/qDHCEw==
    secret-access-key: AgCLvanP0w/YPMsXAqAiaiQ+GgV3uINwki2ZxnxoGnFVTGh41FYHoQO1J2qRhpBk8CkiBnX0ws5gFBFIIhB59h5ZNm8Ps9RuUWOIDm8m9wXgmr9IEg7T26Keifr1xzwZO0Qc++/libJW4pFTeDyqIyfsFbmJwgtBo16CtPXBpkKMz2ZMxeooq7V8b8E/kjaqBmFH169ZtdLeVZDsMm6HhuaC3iNHvy4DiLfG/cIYpEsJc65TfiLGHE14VOr3Zwk/Ar3sPcHVR62pY9LURi6+kSrDwUjPiamHMvrYCdZIWdeJujKKErRFPCsx6WCXhyDhrawIuc0LzLwMue7hBTWgK2AZEcQ84bDI2LoP8OVO3nEd39HdX5R14xJjQa6PWNaugsPieq6KWKhZzlzLflOvkAAgE2A0hTI6CH8lXa351McnI2YdGZK5zITMDYD6oQ26QlWyVyeqTsgs6HtsC7zmCSB0SX4UNAYjfBPOCtiqLLC7cbSXfl1UVaLOUIq+D6JYy2uzP0heFBOEf0CM0AArif3fd0mDS8zvqXQwUqi9I8hlOOqbXmRIYpr+Ogm35Gxqy4nFT5ehTyDWZXZP8FVyDseUfkDg5D+GKeaSmLxkfnojWnYA715fNOtXvbgNNZDZ36XROxlGaiC6U9uiCBAquGwv2Dxvk9EffQ80LPXb2P/M1RTglMIpOd6M0HoKC0RMdEwK296BlYacESlmwIKknu02Om8m/Je9DpSppTAMvUXVj/6Sh8dg0YG1
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials-secret
      namespace: default