---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: flux-system
spec:
  encryptedData:
    secret-key: AgC4CVSYozn/OebC9HgoWBy+g4/Pm2kSkaAyHWSYJ0AGEdJ+awsFGLgEuO8kJ7rDtXFDAOGFkxT4ulWsSulSHq40yntkEEy+y2/FH6dZVQrVOfrr9IaGYm/0znDz4bRb1a0H9ihGs6bPVbQQ0agPAix9ar13mue6SmjcZBEDD2r1cnN/5Q2+0WEFtrViS8SQPguO5/rWRMmxOTCQ9ySl0aDd9NUN6z+RR6G4tMlVuz1D1K8ZWc40WjJiP9j/R8Y+yj12pguyiOBasKILNofGoaB5O+zjFKxv0Z3Uc/R3khrZvxji6XvqA430PwBWWm1t4sMRDw/RewlwXJJdJ5Rp1gVwbtOWvMJbfWH0mm5bxOxevluU4qkGGzNJCAIMNFP4Nq6EU997Mbjzo8RTh0kS+J0/kg0wbz/Q1B/a71iJNeIiEljzrxQhsPHYlfdIf1szkYJIQrQHFYm7ZFXaIXmiFVZsnMnhK71hvdd3W9IyutiQufvgGqrZ3sqyYm5rc1egjhfNZhPqAlpLvgSncuV2da8NFZrw1sYHhToOX+DWAnxbPJ9Q4IKQhDB11tFrVipH02X0pTTpOwBmlOawQwKhe6v6kyunswvyn+PJ7NQhGkwx9GxM99e5mtGLrJmUXFphIj5cuijrDo4H/w4HejAUIVE+eaKrrIMZDeKHERo8uYPsInFqJF/0orLvN1pccQawz3CZ85NUX2uB0ipzn40sDFb6Qr478qqCENIU
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: flux-system