---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets2
  namespace: authentik
spec:
  encryptedData:
    redis-password: AgB6Vf//ngr/RieECybQ9FIbskpJNmwEwwLFIilEa9cFX8hmYSOXKvTo0GkA2ZA/HAiUTE+Av9tNelZKH7+upzBpEYHaa+GjEiQWRuaApKD7zh5tswCbWfjZKdxK4aEIQpuWZuSEMCXe42EvxRfnfBE3onArkaFbDeKUwNyeh6ZlaySMe2XlxWH7B1s1sAsS2APA76e9Vr189LpG4S+RyR12H+BBELQ/xsZ59mtVUX6dhBoLPWwl9Xd3XAP7MON1A9Tswt68WGh5yAyk1kkcqoRxh9RH7nE1bPyNdxl4X3/6R1PtBnSOVAkSP9NfMTrSAlUw42LgaD5ouE+RUPh67wWYckVUxi792VwmB4egHuHWA0zgPS2xbChZ07znwJOh0yzF2tdxxoTN5UH/u5GSm2gwhrpCNrOTpJpK6VY92L3VRBlHT60yfigW8NgbtKoDv8XjayfOQKnrUl43s1uQtuSBLICz1La06hPOACfVtBFk666AJ3o/aHYDqkuQcdRsm/P51JBeY9Nvb5jmgDZaLm1MRrfHQopBtQi1Nbk7O85mkqsFrEgnBFI8EYV4oYPovZQCkBzC/hN5ga25dysUaZdAXlOabjAV/HtnTrJJWYJT41s1f2LkYE9PvjmXz61lzlR4Bt4CTNehxpoBfR3mJ3Y9BzOK/79eEaDsie6CJ89IqIAzVEIgzsni5tvM9UWCvTtNhDFvBJRNnwYSy9fiwSyaLEGLulB40wWR
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: authentik