---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    managed-by: flux
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
  install:
    crds: Create
  interval: 10m0s
  releaseName: authentik
  targetNamespace: authentik
  upgrade:
    crds: CreateReplace
  values:
    server:

      ingress:
        ingressClassName: nginx
        enabled: true
        hosts:
          - authentik.tallflix.ca
      
      env:
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-secrets2
            key: db-password
            
    postgresql:
      enabled: true
      auth:
        existingSecret: authentik-secrets2
        secretKeys:
          adminPasswordKey: db-password
          userPasswordKey: db-password
    redis:
      enabled: true
      auth:
        existingSecret: authentik-secrets2
        existingSecretPasswordKey: redis-password

    global:
      postgresql:
        auth:
          existingSecret: authentik-secrets2

  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret-key
      targetPath: authentik.secret_key
    # - kind: Secret
    #   name: authentik-secrets
    #   valuesKey: db-password
    #   targetPath: postgresql.auth.password
    # - kind: Secret
    #   name: authentik-secrets
    #   valuesKey: db-password
    #   targetPath: postgresql.auth.postgresPassword
    # - kind: Secret
    #   name: authentik-secrets
    #   valuesKey: redis-password
    #   targetPath: redis.auth.password