---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    managed-by: flux
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
  install:
    crds: Create
  interval: 10m0s
  releaseName: authentik
  targetNamespace: authentik
  upgrade:
    crds: CreateReplace
  values:
    server:
      ingress:
        ingressClassName: nginx
        enabled: true
        hosts:
          - authentik.tallflix.ca
    postgresql:
      enabled: true
      auth:
        existingSecret: authentik-secrets
        secretKeys:
          adminPasswordKey: db-password
          userPasswordKey: db-password
    redis:
      enabled: true
      auth:
        existingSecret: authentik-secrets
        existingSecretPasswordKey: redis-password
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret-key
      targetPath: authentik.secret_key