apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  #strategy:
  #  type: Recreate
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
      - name: ombi
        image: linuxserver/ombi:4.22.5 # {"$imagepolicy": "flux-system:ombi"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3579
        env:
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - name: ombi-config
          mountPath: /config
      volumes:
      - name: ombi-config
        persistentVolumeClaim:
          claimName: ombi-config-pvc
