apiVersion: apps/v1
kind: Deployment
metadata:
  name: rengine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rengine
  #strategy:
  #  type: Recreate
  template:
    metadata:
      labels:
        app: rengine
    spec:
      containers:
      - name: witnessme
        image: trithemius/rengine
        imagePullPolicy: IfNotPresent
        command: [ "sleep" ]
        args: [ "infinity" ]
        env:
        - name: TZ
          value: America\Toronto
        # volumeMounts:
        # - name: screenshots-nfs
        #   mountPath: /screenshots
#       volumes:
#       - name: screenshots-nfs
#         persistentVolumeClaim:
#           claimName: screenshots-pvc
#  ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: screenshots-pv
# spec:
#   storageClassName: syno-nfs
#   capacity:
#     storage: 17Ti
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   mountOptions:
#     - hard
#     - nfsvers=4
#   nfs:
#     server: 10.10.10.110
#     path: "/volume1/screenshots"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: screenshots-pvc
#   namespace: default
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: syno-nfs
#   volumeName: screenshots-pv
#   resources:
#     requests:
#       storage: 8Gi