apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: double-take
  namespace: flux-system
spec:
  chart:
    spec:
      chart: double-take
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 10m0s
  #releaseName: doubletake
  #targetNamespace: default
  values:
   env:
      TZ: America/Toronto
   persistence:
      config:
        enabled: true
        existingClaim: doubletake-pvc
    
