apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibreweb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibreweb
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: calibreweb
    spec:
      containers:
      - name: calibreweb
        image: crocodilestick/calibre-web-automated:v2.0.1 # {"$imagepolicy": "flux-system:calibre-web-automated"}
        imagePullPolicy: Always
        ports:
        - name: "http-port"
          containerPort: 8083
          protocol: TCP
        env:
        # - name: PGID
        #   value: "1000"
        # - name: PUID
        #   value: "1000"
        - name: TZ
          value: America/Toronto
        # - name: DOCKER_MODS
        #   value: "ghcr.io/linuxserver/mods:universal-calibre"
        volumeMounts:
        - name: calibreweb-config
          mountPath: /config
        - name: books-nfs
          mountPath: /calibre-library
      volumes:
      - name: calibreweb-config
        persistentVolumeClaim:
          claimName: calibreweb-config-pvc
      - name: books-nfs
        persistentVolumeClaim:
          claimName: books-pvc
          #readOnly: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibreweb-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "calibreweb.tallflix.ca"
    secretName: tls-secret-calibre
  rules:
  - host: "calibreweb.tallflix.ca"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: calibreweb
            port:
              number: 8083
