apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvshows-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.105
    path: "/volume1/tvshows"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvshows3-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 17Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.110
    path: "/volume1/tvshows"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ytshows-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 17Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.110
    path: "/volume1/ytshows"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies3-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 17Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.110
    path: "/volume1/movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: books-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 17Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.110
    path: "/volume1/books"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.105
    path: "/volume1/music"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-complete-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.105
    path: "/volume1/downloads/complete"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-incomplete-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.105
    path: "/volume1/downloads/incomplete"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.110
    path: "/volume1/immich-photos"