apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinchflat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinchflat
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: pinchflat
    spec:
      containers:
      - name: pinchflat
        image: ghcr.io/kieraneglin/pinchflat:dev
        # {"$imagepolicy": "flux-system:pinchflat"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8945
        env:
        - name: TZ
          value: America/Toronto
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 2Gi
        volumeMounts:
        - name: ytshows
          mountPath: /downloads
        - name: pinchflat-config
          mountPath: /config
      volumes:
      - name: pinchflat-config
        persistentVolumeClaim:
          claimName: pinchflat-config-pvc
      - name: ytshows
        persistentVolumeClaim:
          claimName: ytshows-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pinchflat
  namespace: default
  labels:
    app: pinchflat
spec:
  selector:
    app: pinchflat
  ports:
  - name: pinchflat
    port: 8945
    targetPort: 8945
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pinchflat-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
spec:
  ingressClassName: internal-nginx
  tls:
  - hosts:
    - "pinchflat.tallflix.ca"
    secretName: pinchflat-tls-secret
  rules:
  - host: pinchflat.tallflix.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pinchflat
            port:
              number: 8945
