apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
  timeout: 3m