apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbot
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: bbot
    spec:
      containers:
      - name: bbot
        image: blacklanternsecurity/bbot:2.8.2 # {"$imagepolicy": "flux-system:bbot"}
        imagePullPolicy: IfNotPresent
        command: [ "sleep" ]
        args: [ "infinity" ]
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 1Gi
        env:
        - name: TZ
          value: America/Toronto
        # volumeMounts:
        # - name: bbot
        #   mountPath: /root/.bbot
        # - name: bbot-config
        #   mountPath: /root/.config/bbot
      # volumes:
      # - name: bbot
      #   persistentVolumeClaim:
      #     claimName: screenshots-pvc
      # - name: bbot-config
      #   persistentVolumeClaim:
      #     claimName: bbot-config-pvc