apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian-livesync-couchdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian-livesync-couchdb
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: obsidian-livesync-couchdb
    spec:
      containers:
      - name: obsidian-livesync-couchdb
        image: docker.io/oleduc/docker-obsidian-livesync-couchdb:1.0.1 # {"$imagepolicy": "flux-system:obsidian-livesync-couchdb"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5984
        env:
        - name: TZ
          value: America/Toronto
        - name: SERVER_DOMAIN
          value: obsidian-livesync.tallflix.ca
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: obsidian-livesync-couchdb-secret
              key: COUCHDB_USER
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: obsidian-livesync-couchdb-secret
              key: COUCHDB_PASSWORD
        - name: COUCHDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: obsidian-livesync-couchdb-secret
              key: COUCHDB_DATABASE
        resources:
          requests:
            cpu: 25m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - name: obsidian-livesync-couchdb-data
          mountPath: /opt/couchdb/data
      volumes:
      - name: obsidian-livesync-couchdb-data
        persistentVolumeClaim:
          claimName: obsidian-livesync-couchdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: obsidian-livesync-couchdb
  namespace: default
  labels:
    app: obsidian-livesync-couchdb
spec:
  selector:
    app: obsidian-livesync-couchdb
  ports:
  - name: couchdb
    port: 5984
    targetPort: 5984
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-couchdb-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
