---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sftpgo
  namespace: flux-system 
spec:
  releaseName: sftpgo
  targetNamespace: default
  chart:
    spec:
      chart: sftpgo
      sourceRef:
        kind: HelmRepository
        name: skm
        namespace: flux-system
  interval: 1h
  values:
    persistence:
      enabled: true
      config:
        existingClaim: sftpgo-config-pvc # PVC for persistent configuration
        mountPath: /var/lib/sftpgo # Mount path for configuration
      data:
        existingClaim: uploads-pvc # PVC for file uploads/downloads
        mountPath: /srv/sftpgo/data # Mount path for file data
    service:
      type: ClusterIP
      ports:
        # - name: sftp
        #   port: 22
        #   targetPort: 22
        # - name: ftps
        #   port: 990
        #   targetPort: 990
        # - name: ftp
        #   port: 21
        #   targetPort: 21
        # - name: http
        #   port: 80
        #   targetPort: 80
        - name: admin
          port: 8080
          targetPort: 8080
    sftpgo:
      admin:
        username: "admin"
        password: "test" # Replace with a secure admin password
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: internal-nginx
      hosts:
        - host: sftpgo.tallflix.ca # Replace with your domain
          paths:
            - path: /
          backend:
            service:
              name: admin
              port:
                number: 80
      # tls:
      #   - hosts:
      #       - sftpgo.tallflix.ca
      #     secretName: sftpgo-tls-secret