apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftpgo
  template:
    metadata:
      labels:
        app: sftpgo
    spec:
      # securityContext:
        # allowPrivilegeEscalation: false
        # runAsUser: 0
      containers:
        - name: sftpgo
          image: drakkan/sftpgo:v2.6
          #     # Just spin & wait forever
          # command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: ssh
              containerPort: 2022
            - name: ftp
              containerPort: 2121
            - name: webdav
              containerPort: 10080
          env:
            - name: TZ
              value: America/Toronto
            - name: SFTPGO_HTTPD_BINDINGS_0_PORT
              value: "8080"
            - name: SFTPGO_HTTPD_BINDINGS_0_ADDRESS
              value: "0.0.0.0"
            - name: SFTPGO_DATA_PROVIDER_CREATE_DEFAULT_ADMIN
              value: "true"
            - name: SFTPGO__WEBDAVD__BINDINGS__0__PORT
              value: "10080"
            - name: SFTPGO_FTPD_BINDINGS_0_PORT
              value: "2121"
            - name: SFTPGO_FTPD_BINDINGS_0_FORCE_PASSIVE_IP
              value: "127.0.0.1:8080"
          volumeMounts:
            - name: sftpgodata
              mountPath: /srv/sftpgo/data
            - name: sftpgohome
              mountPath: /var/lib/sftpgo
      volumes:
        - name: sftpgodata
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: sftpgohome
          persistentVolumeClaim:
            claimName: sftpgo-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sftpgo-http
  namespace: default
  labels:
    app: sftpgo
spec:
  selector:
    app: sftpgo
  ports:
  - name: sftpgo-http
    port: 8080
    targetPort: 8080
  - name: webdav
    port: 10080
    targetPort: 10080
  type: ClusterIP 
---      
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sftpgo-ingress
  namespace: default
  annotations:
        #kubernetes.io/tls-acme: "true"
    # type of authentication
    #nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    #nginx.ingress.kubernetes.io/auth-secret: nginx-secret
    # message to display with an appropriate context why the authentication is required
    #nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  ingressClassName: internal-nginx
  rules:
  - host: sftpgo.tallflix.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sftpgo-http
            port:
              number: 8080
---      
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sftpgo-webdav-ingress
  namespace: default
  annotations:
        #kubernetes.io/tls-acme: "true"
    # type of authentication
    #nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    #nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    #nginx.ingress.kubernetes.io/auth-secret: nginx-secret
    # message to display with an appropriate context why the authentication is required
    #nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "webdav.tallflix.ca"
    secretName: webdav-tls-secret 
  rules:
  - host: "webdav.tallflix.ca"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webdav
            port:
              number: 10080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 17Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.110
    path: "/volume1/uploads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: syno-nfs
  volumeName: uploads-pv
  resources:
    requests:
      storage: 8Gi
