# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: webdav
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: webdav
#   #strategy:
#   #  type: Recreate
#   template:
#     metadata:
#       labels:
#         app: webdav
#     spec:
#       containers:
#       - name: webdav
#         image: bytemark/webdav
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 80
#         env:
#         - name: TZ
#           value: America\Toronto
#         - name: AUTH_TYPE
#           value: Basic
#         - name: USERNAME
#           value: tallmega
#         - name: PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: webdav-secret
#               key: password
        
#         volumeMounts:
#          - name: uploads-nfs
#            mountPath: /var/lib/dav/data/
#       volumes:
#        - name: uploads-nfs
#          persistentVolumeClaim:
#            claimName: uploads-pvc
# ---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 17Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 10.10.10.110
    path: "/volume1/uploads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: syno-nfs
  volumeName: uploads-pv
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: default
  labels:
    app: webdav
spec:
  selector:
    app: webdav
  ports:
  - name: webdav
    port: 80
    targetPort: 80
  type: ClusterIP 