apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep-web
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: karakeep-web
    spec:
      containers:
      - name: karakeep
        image: ghcr.io/karakeep-app/karakeep:0.24.0 # {"$imagepolicy": "flux-system:karakeep"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: MEILI_ADDR
          value: http://meilisearch:7700
        - name: BROWSER_WEB_URL
          value: http://karakeep-chrome:9222
        - name: DATA_DIR
          value: /data
        - name: TZ
          value: America\Toronto
        - name: OPENAI_API_KEY
          valueFrom:
            secretRef:
              name: karakeep-secrets
              key: OPENAI_API_KEY
        volumeMounts:
        - name: karakeep-config
        - mountPath: /data
      volumes:
      - name: karakeep-config
        persistentVolumeClaim:
          claimName: karakeep-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: karakeep-web
  namespace: default
spec:
  selector:
    app: karakeep-web
  ports:
  - name: karakeep-web
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karakeep-ingress
  namespace: default
spec:
  ingressClassName: internal-nginx
  #tls:
  #- hosts:
  #  - "longhorn.tallflix.ca"
  #  secretName: tls-secret
  rules:
  - host: karakeep.tallflix.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: karakeep-web
            port:
              number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.11.1
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MMEILI_MASTER_KEY
              valueFrom:
                secretRef:
                  name: karakeep-secrets
                  key: MMEILI_MASTER_KEY
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: meilisearch-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: default
spec:
  selector:
    app: meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep-chrome
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep-chrome
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: karakeep-chrome
    spec:
      containers:
        - name: karakeep-chrome
          image: gcr.io/zenika-hub/alpine-chrome:123
          command:
            - chromium-browser
            - --headless
            - --no-sandbox
            - --disable-gpu
            - --disable-dev-shm-usage
            - --remote-debugging-address=0.0.0.0
            - --remote-debugging-port=9222
            - --hide-scrollbars
---
apiVersion: v1
kind: Service
metadata:
  name: karakeep-chrome
  namespace: default
spec:
  selector:
    app: karakeep-chrome
  ports:
    - protocol: TCP
      port: 9222
      targetPort: 9222
  type: ClusterIP