apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secret
  namespace: default
spec:
  encryptedData:
    FRIGATE_DOORBELL_RTSP_PASSWORD: AgCGo+z+bjgvMG6/ZA4gm31EOc15o0VyxkVlCsUn6LiPKyJXDiuA8lFm4MHyhiLbHYoJFYsojHyfzg6NVENyqG0rkRAc5gEmvog2VIslAOC7IylozjSxujyfidmCnxvJt8d220lIiETwawpBXJvxB2i6Y/E/8hj6aE6Dh72p5l66GcSnIRMVWOD0kqPWqJRr4jIw3x/6GJDkoCHprF5ieo/b9Kl5mMkSDcLumkMfLS8iZz87CROypalVU4SuOhRE02HaXMk1lHkK+UmEgr+CnECATIjJFbeoQJWf177yVPZcWxx3AFtwPzwi6McqhnHbyJY8C4Z/56qOE3wRtvW2gcOIMRhjr+rtnd5kobWvrb92ZP3mwHIw+U8GEsorkjKBse9bL115BbUu3E34es31Phz66OujK/Y9v1SrzmDKuMGNnbjDmJkKBHXGQRAj/NAUAT3005HeMNR5bhdQZbLHX3VBGiHqcRWW4jvuvj74TWCvADA3kuaavWXzWPYXAtOcdAz0sApVCozk49D8forAndJe2ME+9DhloB/yDST5EMUfKd8tpiztNIAINCPNx4PRC8H6PHo9hWTSj2n5XOXunYFebWAt6Qtp1DFpKlarWGK4+6lTFUKY4us0N+AX9Yf1IdcpQEt/ixBaUylWiQXGDwvYWEqbkLfgBXKa9WM1rkSnWTxBXqMTWq54Tw1ADY6mbu/emUuhLV3a2xzOlJbKC+s=
  template:
    metadata:
      creationTimestamp: null
      name: frigate-secret
      namespace: default