apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secret
  namespace: default
spec:
  encryptedData:
    FRIGATE_DOORBELL_RTSP_PASSWORD: AgAHepNLQG7+NSntd1Bb8kZpSbXT4PwACznwltGowAsMgvgB9Fs+m8YEK98ZYi78OK9OiC9yrHqAHP/hWGXMhDpTMoNAoG4tpxTC0qbwO3AYxhyjrpeMB2nCarepd/F0SYkpQU2xOd6bj3UK7kcTd4u3g3T4AiIU8yrUs9F36p7IcIjFEzVfpgCqPha/7YCJxNdnsyowpjwwW7uyyzfep1T2PBohzAu3e9QPkY7cePPT3ZVGGBHuxK4QKLbvdpRJoxr8dPmtDe+2HnT/S/V1qErKim1ssHdT8cFbsRlCREuyEXSCaTKz3+xwrAlPmnYbe6OQNMNh0++ggrhRM5W4XdsXmMXHfypMRamUmOxFR9CqFUmAzrWQ2vdW1NxjOfzFxw8+OWknix8a/ianpChAYE8RgF2lQwPTMr/EQQ4Yt3eK4UjG0J004Ht/U69Uj8N/xhCeSpvv0YwbfvruibSwhYBV5r/6JvN+eRjgJsoFO/lTHvn8LmL/ib9tP/at/vwnjhAngWFDukmnlxKwU5AEzALESNlgefqlx24NA2SWhPG4rKSAJ/ltPqWbFmsTkgL+1YXd/LTTEg1dV4c7AxNC3FrxXoja6oXHuZZ4s9PHHYcuHFlITiBP5yWe3CiCAj4fCJ9wFjZ/fhrmtrXepXaow7QSn1UJH0GZrg08NsoYz6V3O7FCMKyrTTpl3DQ7kcXwtxHRfLoVrr/wc/Rm24JDgg==
  template:
    metadata:
      creationTimestamp: null
      name: frigate-secret
      namespace: default