apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secret
  namespace: default
spec:
  encryptedData:
    FRIGATE_DOORBELL_RTSP_PASSWORD: AgCxLahdQRFezFX3Ai5vjgvyYhnts0JffrSb2VJtccAReKQqxQ9WM59nY4OpKAiDvZbDXyGnsM8b7hzeyDRvYieYALhYzBVAmjrAWBpi52+ZYpztHCTnSttLug9Mq5MeaaUw1+VlSEWnG7zrAPzos/Ab9MwkU5wfTtitIrX1WBzN+wQ6Wh1X3rWmxkA2E7L17UfC8UvufKxac8pxUCzqeqNLIU5XvTMiJF2b8+qeFjS65zya5myTMeU1kPuh47v1sxy4HiUbzVWBMik+TCFIC/pw0L3mZN/oVTA5n132ce6nhFERadRrTm2/l8C/QL10IrDXDTBqWN2KKsAmM+jFBxaX0tfZKVsmVdNiQqWJMPZ58K/Io17jVnFktmJLz7UHXHMRtw3NSDt5Q9DE1NSXZGMTSykBIBxBnRb3Tn1CoHOysMuYNrThoisk2oQwYhfgHQth1im+UZOm1RfLjPn4Ib1rhBnNOKgb8lD2sbdDuwq1033gI6ZZFnIuKeDUjEexrW9uotBEs8T95jBx3/otIuS9Ftk8ulkVx0og1imOz8RI7cLerupx4jFTCO7CJRl1sNC8jtLkT0a4bV+qpY0KNaGB8aDed1Hw9x58IpDWCD1rDXR3akkl6GGhRZdjGMqosLnwS3644222VV+SLLixS8VIvDI6+i4kT7SF9jSoYo9eASGZotdp7EPnQx9NbEva6peUh37S9Cc=
  template:
    metadata:
      creationTimestamp: null
      name: frigate-secret
      namespace: default