apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secret
  namespace: default
spec:
  encryptedData:
    FRIGATE_DOORBELL_RTSP_PASSWORD: AgBCGI8YJoIWqXVj4AhXC6OHhbFxusBm7pnL/2pLPE5h5jb0dEcIS7Ur9aMr9MoX5xNG2I2NSAruUwxYiZ5TiyIcn/sJ8kOxi6Vf9gR6IV2Ay9lP6CcvhlzVrBZdi/OCQHgPTd7s9pRjGK+ETRV5oc7IoPxc+qWQ6vMGYiuX2uXLgK5kIx8wBeMmcKXri+swz5ItmchPVnx/vaBQOMbHYj4+7EAJ/iZ3SjSzoXWU3g5UGW887hZ+qI3Y1Ht2VYBKJmmAd215NoZw61bJanJUREpizv4rKg8fr4NVX9mwGa+OAMtzwXA+JFuETvboKKItdk1uWmJCIynS1g1E09NLDP1+vuSOXoryJe1j/2rFO6lAdzBVa85WVof2lKlkVEBbHBPESCqz983aBo/y+Dbi7okdtGIxawI9wqsN4kqX/GWb64ptLdfIww+0SMwCgAxP+A+5ZVi3CpQvB61hoSkjOY9DYAWvkHyAmsHiOmHQpgVrqCBY2ICBhgOGChH/T6caG9eWaKfb+fclVI+pbx8/zbHaoIE7v3QlqJIs9CXrkbKeoyhbYpUzdRcnuzRkVsqo8EUgn8JZVt8Czyl6xg9x1RGqtq2gce6882a4xHn/6FirRYCjjnw4SSp7Nh0AI13xWU5PVgAW84XzMg8c+3GalEQfYvwPIi+xeyDVVaE9PTPBxQNH02+rFaBDiulbHe33jLtoxSIbzMU=
    FRIGATE_WYZE1_RTSP_PASSWORD: AgADUJlwECFl3mJVuduSKrOW40fsaXkC3uy+E/RSCpA8wSFEoAYUTLadTQ8OaEntpYrM+cIlGActPac4UsZyiIHzPJcGBzPg6qxU0Wj9dAnYlpRa1bRNnRpQKPsPhk9z9rGFvK02ODW94BYLVJ+gv5buVZTCVa040yZcZ+/REIXsGZbzIjWc17SAsCeyzixlGSFEs80MFAe4c3b5PY3QEuWpyHulFbBvIq1+9dDDfo8Srr6nmNlgqMI0qGDL/ZK7wjKs9lVetQ946jDaCl23ftMwNnt+N2/+J3sl6EVCJXAXb0T/p9NMjQiYqoTB0eTIXk+tPON5lqeBfQ/58dEQQ5NU4dblvFvpLIEOdfXimsS7LOBlh8chcun2R5fzopk419dRsoESpmPX9htLDX/nxqqGXEVztTymf8vMsOsMWVc6rRJl12T3o5rYlnpOAoqvavsUq6DYcIoBh78BCCJM+/qSbVaoFJ56iFSO2GJ7vu814ScZ4LgwHwxubJJ2DE/vFvqFegIGWgObmJNvlw1blQEXLM9MlhvmGQJ8BXCH+HsHhhNl9iG5c0aMJ2Q8VypleTBJWTabqCUoSl0C+e65DTj9brOEbzhP1BhJDCkW/PFhjVmfliWzquXC2Uh3FvlCYcwqJmHgp8CDkBxP6L6CmZxtGIT48q0KljbNeyEblesub521r3keFvqWXfomQ3HtQRYQJkCVDl7DDA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: frigate-secret
      namespace: default