apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secret
  namespace: default
spec:
  encryptedData:
    DOORBELL_RTSP_PASSWORD: AgBzWOshvM/5pPMfIwCpSCMHoa+GAeHgWVCuk/7pELQsz+Fuj0xDQ/WP5zYkBHIQsqVKHDHzALq/b/JbreEbrM8rJLblE0WwdBNjpspW1AZn59slUJ4akVUqC1lRqTg+9b1bjrBmeK3jtszJ+2Ei5h/qAsU13wnjdG1LjYlmt4Mhxn0e6i+vJjy6iQh52bHABjTOLD5FQgLGEQtf/CdId9hgpx884HQ79cnRJ5lyuH1SGGsCw947aICSG8uSsdHegM49BtsRM/0OLN6Dn2qvbRUYvEEGegqIeuSJo9YDfC2FQTY+MrNfU7pZSH12/qupsm4Axgqm7BKts05oEjnPBSDUWq/cgag0rtl5jhPHAqYj91/SVw+rfgSjp6eAAlqOidjS5UJHAj8OyERquP17ydEzqqkYUigcaraN7Knz5IBktVnz1dTi5m9YK1eqUEBhjp99eYCNk1ftyGcgFckbnEAmTagvU0zdVAUlGqpbknq5UNngp7uHHDOb7k+qy7qdVgJWvXYqIJORSVRhUXUjwG6pJHnxOrxDmqQ5x9WXdI0rFjTRVBeNNj6WU3Z4IXqOqI/f1c5la9uqolPor3UdpXzhrIxwIB/h8k+TlnLAoXuffXYYLwd6DOgpHb8tjCOQQjX2I5ClSkTh/om/94nPAWIpvwNOQYPxL3GQUrM+5qzB1lN59Uv+Bui62/nmUMw8daQKXr6dwyE=
    WYZE1_RTSP_PASSWORD: AgCP63tC0nOmrhWmSbsO5XmPvNMPqHZ5vhkieVhaajpCnRqtXf/ugwnxUenCWOoqW7OhADn0T0YeU4WQDVNlu9SzqsXGkSTgwIC/5dc0YEb/I65my2RizMVOSNSJgtQqPBYJegLaBmaz5yNlGp+R8GFH09ug6LEzHBWrYrcbphrsD4hJpU6q9DLuskzUiKS9NVs6r9FHCtVr8efpFGuUOYPw65HM6t6BQErAjxDmbwYhp3RcVGeBQT/8paybf0jFJdO6WokKylFOACqA7X1xJ9w+K7nMQQw0J1OUaqIC0t6DwDc76rO67hqTXsEwcsY/G++WqHqUI7V6YtESOrcpygK7A4DwSERQMax9ruMfMiWOURCBZsJGCiDgj6Xy01yYRYYcArdO35YGSHjdMzYn+gqiyRTbGUt4qv45m9xMmBGJV+gJSjWbWC29uuqfNWaQhpv6//etEDlHv5xkrfg+qTnmGqGPi3uRuzH6DQbbQ48X3XPuRPmFFB8xf8S50uhYxCau+6E5IzSGKQMPrCc2rCao8qjbQtmGdD/4oxgZ2jEajHIG4hEIJ8pE43dAWNJckW1XvLJ6lXUSNxdCaewz8NUHpJKIqY6G96XenI+N3s9axAXOXGvBsVNydJLSijzh7hYntYNEK+VYR8Ed828aYAfizBvsS19lASzEtIrVL7gA5dFVyeQs77xTCowppP3tKSV+tdBXOMoKVQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: frigate-secret
      namespace: default