---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-recording-pvc
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: frigate-recording-pv
  resources:
    requests:
      storage: 10Ti