apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 10m0s
  releaseName: frigate
  targetNamespace: default
  values:
    image: 
      repository: ghcr.io/k8s-at-home/frigate
    ingress:
      enabled: false

    service:
      type: LoadBalancer
      loadBalancerIP: 10.10.10.66
    env:
      TZ: America/Toronto
    #envFromSecrets:
    #- frigate-secret
    #podSecurityContext:
    #  supplementalGroups:
    #  - 44
    #  - 109
    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1
    
      #persistence:
       # data:
        #  enabled: true
        #  mountPath: /data
        #  existingClaim: frigate-data-pvc
        
      #extraVolumes:
      #- name: frigate-data
      #  persistentVolumeClaim:
      #    claimName: 
      #- name: frigate-config
      #  persistentVolumeClaim:
      #    claimName: frigate-config-pvc
      #- name: frigate-recording
      #  persistentVolumeClaim:
      #    claimName: frigate-recording-pvc

    #extraVolumeMounts:
     # - mountPath: /config
      #  name: frigate-config
      #- mountPath: /media/frigate
      #  name: frigate-data
      #- mountPath: /media/frigate/recordings
      #  name: frigate-recording



    

   # nodeSelector:
   #   feature.node.kubernetes.io/cpu-cpuid.AVX512BW: "true"




