apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logs-secret
  namespace: default
spec:
  encryptedData:
    password: AgCV2hUYeESgi0z6KZzxkzXPUGK6eNX39j+OYJ0dqbv4EgtbedD7MwhUvGmNWaqLSCUhhyR48yQYqZo06MKWs2jgA4ioA9LiYTxyXP/jeNZ6N005tmCE820zbSRiV465iGEvhmh0XGCly/MNMppKxZRxcvysl4hHbyWLMDGCu+rxlUFBtJ3PyrYz2iCIb1Qot+8KAdNa6gEAKQZjLwb+TgAkDoS2KxHPdpszDT2talRQR5pcI8Zl6yuxeR7sFCYR8SITOiOUTyseOwSp78BglMNTzrB1F0EZ7xmLdbLsP25Wg7nW6ag1pkEl2vK/AUV9CCogCcz0Dz1RFPC+sSyzXKQX5O8s4BUVxfp0TQFnJfOjsw8BCaX6UbUfLXyOpyVj/nymAaW7m8jhPnO+dlYiJ1vVcQrj0E3kcy5JO/Er80fCv2G1yMpEfZnH1pM1bWomGYGGKk6GJYynCphDQrpgFn3fMzZUis154F4kzwfh/JSY8TLhDo85B0+jBXtQMQUyUF8joscrJkYGYt5JIF5R1T2RqNPQsI/3Fr3sQ66KUG6RshEESwVSXY86Eo6ION3JTNa2huKoHnAj/TbxhrXBdt1Z7H5BNYrCIHy1XXq6jofeMoBzXB8qksv0UbPssSU/sYzMvpcVP0cyvnBUdXcn/213PINuyp1belrbyPOdaSxf+696KziR9kMO54A9CZELCeAp0HH7wc575t8jxDkHHAwaGwlYZfTvlTQxqSaVwXkpX9i6vwXfTsjlH8uds7Lmr7q5X49k0CtIhBPik/JC5tXM9eOEBMTA8lUO0In4AR6oVCqm8UCvPTXCbqqr/2naVqmfiDwO3Z0LGo7SI6IDLfAc3i3swb7QaBuw0rdueQN9sA==
    username: AgBQhjHH30yj3w4yDyurD0vcb/LBxP2bQBZm14GhWxjtzlrDDuKYpgIOXhPoOG1XpG17EMJgY6k3tTI1InpZpIzsgBi9NQ3DaTByGHQhv7SoUrRX0vxu8jS0MfP7uueEJCeUPgwC+VFDbP7ITxoNZz5Jsb8UwVZdu+AhQsGTdf/Q0P0VxrJeW9sMpcgB0p0M4H1OAeLOa3+vT7YKEjQPj/meUBE9W3EJUS9j5PdSvhvwZ/mAH+HnVNjkMdxIWjK9bAdfk/FbWgxZZBriXZ3t9Lu/cNv9rL8PPL8lZop8L6FBFXV1nD5N1xb60ayfRVmD0hP9PbIBCyJBioHvUe66V1uVNx07xt1797Df4FZb5+ts95/59a+G07K36U+owwXhDTWX4kX34IedVA+5u0bhVU34lvc+NN1X/QRYCaVlKLkGCvdIwoZQSZVqdD63lrPpUf4cuSKEiw3z3azUrGpSKS72Vas40pyIzFy11Q9BarMpFhO9RtELJAevq4LqduX1ZsKGVwd4J65Jo5c8Fiu81VXxOIMXgTQlbdH6fVVB7medSXCACUEJ7otDg8MC0LXTSiqPpKwub6+X4HWowph9dmchLZ8GABHO8caX15o1+gpS8RDSP6FIeUOWXsVb+2nRYZmKwOuu+YjnEsQlsuYsUv4x0aX3N+3uzgbholzRtMmE0tfBDvxyyLFUMKgJwtigfKBnyF7H0r8=
  template:
    metadata:
      creationTimestamp: null
      name: logs-secret
      namespace: default
    type: Opaque