apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: metrics-secret
  namespace: grafana
spec:
  encryptedData:
    password: AgBYsNi/0OkpDQr9uFXqqYVxb5+WU8O+pTFaftMRbREmhqSL++IBQcSkVI1isU/tGnOmTKSy47PUZ5FuwxdmzIvNENXKAAll3gFktcl7SS0RDJWmvD0+CX2IoyCFZ+Af8vkhhMTOKeX/kH0rLuxE8WjhfUuchxsn4tATHAYTXvwchyEI7ydmIkKKXewUpQpiQc12fjMXFY8AXfrcBAbZPciCF1f9ixVRxmPNVJ6STfiAa4o+vonmINLphm5EAyyj4BRjqfL/yfAUn98oaJ9QrKsfMEDHbSy6NS9wBz1A8K9ydICr3prfbCe6lhvKk3z8kZbpRPbefb84AaQ7xlVGz+U+0HnH1+rCbtmYDTlFghPuVn46CZpARLe7ukirDBpOxuV6agMdVAfBgoau7OoSGmCOaQdKp/jqbMz954LgBux/2d1i+JyA2WmEyHR/QIUx6zM+gFkUpxsC+DeEOOfXF0p9cfUGVfB7CHsmV3EogFTLjXTeITQNTOXCq3PWM5DIaEdC2Mgxx6CyFNEtOgGasLBOwlR6DW3NITTO2Knt48CXWLR9V0FGIm2U2DoesfSziq7QJlGuvxZglamLm3DKVXBnpH3VBbk0qk/ugvCZB3+c3qfrzQpAwV5DoUPFyB6Nyuyao/W+99Cxl/IMq0c7fxJYQfhJm2UPhHFDW6h8ejOjNw5ajaw0raHDLwQeMfxySEeS/zxfVMZJ0nTaL9huiQzRskeDHyo8S8UQu590B2ENoNekHclsQ8/Z5C1KHaT2N7oy42BqRAy7WgGUaHeuCADPMJFGr2dKbwrnbc9kvxN1tiD9xc9tYI+1C/TOl79VwIXqbCu77lrh4zEoa/E9fu2EjkGvWqIP1SYR1WTiph0Zog==
    username: AgDS2+2z+8+F74vILJGqe2joPgmaXOT45re980G9PKyAs4ggYpszUVfssHhgRP/NG203qb+/b5v1Cy1gvtRkr6UIm0Q7M1ptMhJAuxc3rJhorskptlmaRqxOIV+YklywvgPmh4TGTnpHK1DHnVdWD+JMKoCoxbGTf0yE5U+rOKndVaIOTlxvVKfgkhYaERa3hP5Br/WngABebvEqm1NB3vQ33ali8Lcz9jENGZTTP55bz71iv1ynYZmYff/cDw2JgwC5nNEDy03NNzPlJd7PDR8dA3/9E+x6AJVrCOmWrU4yYjybeN2D9qG81QwdSijFCyk3TLDw42zjmqYxeUuTkzJHteItyM0eDpjqDoCWfNg4Q6yRY45JycPV2I6Z7IScbpI2rz6BAF/fl/N4onsqIt+xIPH8ssKPakRE8NAmDc61VYNZbJO2nD7vXgyqp9x4d+Rue7XVroBY5taCJMhLFAmh4+pwsVChHA8S7UbuDJmUfRSb8CeHvZ/lizfbLncQs1jnZmHKlHp9pnmP+4XYacPxYF7NVFQbGpYqRHKg6+ELYBNrbVU+uezBJxynRFb8+vWJEEOvbAq62yjKiB7Pf4XWZBOUL5X7zOvBk8NB9SBfhbGTw27un8RZYgKATRltp1BGyx0wCy4+wXv1//ChtHATyi2tbmnBPLdJnNO4WsLILsWyAtFvIavAVsWYNOpr2r7/wAaYkfnr
  template:
    metadata:
      creationTimestamp: null
      name: metrics-secret
      namespace: grafana
    type: Opaque