# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: grafana/grafana-agent-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: grafana-agent-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h0m0s
  targetNamespace: default
---
