apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bloodhoundce
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/SpecterOps/BloodHound/tree/main/examples/helm
  timeout: 3m