apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-secret
  namespace: identity
spec:
  encryptedData:
    client-id: AgAiRqLhMpR/boCbwZLcEqUclwF8Ja40ZxdcngRUqaGChZZyeZSQD9gNyXGDGQ+NQBzR0nWEA73K0KvO5xj+6kzlmBiqDYzjXKS6HD6D/3Cdt11BJpovqrr5TWIY/o/Xswt3Z/qHQX182cTQ4D3lSwCsOCQDZDk12OUozJGLy+5pDLpRyvoj/RaazsAyRM+x7rbnNnz8qU2ebhd76vKEZpQrs/D+qm5To8tiNu+KNMd2qJbF31zsAkWqrFFrNZNCj/Q5ASFuUNyLObUXrjfdQPqXqXoTexOHucrP4K7LDAT29tUfgeM1VT9TAJtpw9ndfXqbhkmbzvEUdGcQIhSP1BC47kcXm9BHBos/y8pUuUUm9fl/yojlB774vG2yKF8zoh6tkcZWRR/ZAFFa89dHnmnSpoM5uCETqMlPtWDD2C01isc2/o1lP02ftTuWmh4it2paOVBom4vwzorgO9nog3/0w0ejGl9WxJ2xpwXephA1ET5sGVrlUw0x96yDPDoVOg5q42Qsr7vnlnkvi49UF59WBjLNKCP7cC2EoxmkQyD/W3vYemQcFNk0ub6/kavyijTxMxzFnsnM9cQafmwpQfC2czB8Kvw/PQE9f/LPVPvTlu9ST/f9SGJoOHYhkqyRUSfycTqDDPMOjKC8zD5Bud2Fkiq4TgG9lWdmtSXxRTP8rbasOl0rMsMQfnsf5sLNJsR0yCYZRSvBD6dZ
    client-secret: AgDSYxYkkTeq9nSswgC5szJ1VUt1vvu3YNI3ryDY+PWYaVEHrq2teroxIj8DnkyVOpcwySEKhSmXEVCQukRR1RQfnHWvv9smrwk0QTMod+6aoyWI9QtL4RS1fDsmiP2FtqlBsyqKgJOtjHi3WoE/4v0wXOVdBh/N6Tpsoe2E77Po4XB+1IBLK52wdlRWgPsocEZ/aKHruCi0Ly9DVo30/dLmA+id9LZzrNR/9BSTwXYMaLlXO7udIHZiINaU/m8zeF9R2z/DYCAE7r3YtFu8kn6rfT1fZx7VpeTy3lKgWdW7qBsHqA9g1TNSfzXj0/716Ksj6XNXm/IpGfSX79/T7ikQm3IDHkme1QQaUmHi6zYX7AXH8QY9jX6Aeiqu4BBe2Yld3CHYt6H/JbeUT85uOc59NWJEbXX/Q9SjqwmcYGJjwN66rjyCB8KMYIkz0WuKeCL2n+FIdk4CQ1+KVgGiS6qiTB5lUysOfG3kJCdog44VXR+pvu6lpMgKFJNFGsSYu3OFmfmmgQbHQ/W7cEw7RfCi+IoLW7bUXUb4Dmife65n72vw5IPTxVU8lKK6wN8J09fwWVCqKJzG2Br+N+Q7tfgbBSG+X9ff+NMF7jXA26mgAxaewCsrFafRh47WuGIdTHJTfNpbodXxQTukuyawgFjXpApTKliv2BaLfCODQW7xrkgN2R/stHqF+Brgs0qtxpdZPdEcQB66D/a63Ry5dxGjgFfKpnHtXczy3o/ccznY7w==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy-secret
      namespace: identity
