apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 5m
  releaseName: home-assistant
  targetNamespace: default
  chart:
    spec:
      chart: home-assistant
      #version: 11.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  values:
    image:
      repository: homeassistant/home-assistant # {"$imagepolicy": "flux-system:homeassistant:name"}
      tag: 2022.8.7 # {"$imagepolicy": "flux-system:homeassistant:tag"}
    env:
      TZ: America/Toronto
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.10.10.63
        externalTrafficPolicy: Local
    securityContext:
      privileged: true
    # -- Enable devices to be discoverable
    hostNetwork: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.org/websocket-services: home-assistant
        hosts:
        - host: hass.tallflix.ca
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
        tls:
        - hosts:
          - hass.tallflix.ca
          secretName: tls-secret
    persistence:
      config:
        enabled: true
        existingClaim: homeassistant-config-pvc
