---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-secret
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgB5g/Bw2SvjpO9n5wLOn/JgOKxR4NJ1xzSt0n6BmX0hXpj1KcPOWHs3wOMjTV9YUOg7Y4Tax4Vt1vhrLhZCQf6SGQ4onv3k98XUMcN4PzJs/6yih+gSdnANR9HZhQGhH5h51M7hOKo/o7W1BVV+5rrAtfCdSKj9QSHvtUwe58bShrRIgSOwx1ooLkoUyY8cTreKZzbqK5IJkVnWNarEXxFIKoeDuSC36vgoKIBsU3XeEUlL1r8O3FcCnsaK45WbCxQhikYw+ZL20c1IU/vf2n0Ia/vIBAqR04biwsl/z7yslHYsWsvJ+m7QGxcP4AbQs5vY1fYjdKE/TddSpzIrv/OE7v9NFt/XbgAneqjDd2t51lymlcXOL80Ukya6fU1JC4P+CHxFMhVL/IQkWC9OZkmcA7Lbi2uQf83OP9GwUhwAn3+2UZ4r9mVkebd3DJnNAVHJBM3/eGUeGhLY/70ezkU3WxzxdQgK4apAQy1JcrzXQBNpmDtbcv1eXFfLNMFvVwmbZEwqHp5DNS5krozP8mPCmHcOlpQDyDK1rR0nv/Dvqwg0YOj31R8PHyLtCsAvAochx1ZIXBPJAEwmed96Kj1NghLBK9IBSCj102R2zqUyODDsyTX5r2WcHm3T3XBkABAeEyz34BEhm3vALQX0eGxclsj7V7fXuDIaangTrZ0/M1/xGx0aKHVvYwS0vX/nTjicZVhMoyxLdV0K52Y2PHNVsIVc2Ll3R+1NhH+hL8f/ybfd0pp6iDLOYlOW
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-secret
      namespace: longhorn-system
    type: Opaque