apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secrets
  namespace: default
spec:
  encryptedData:
    PLEX_CLAIM: AgBQkNIK2NTeituR6n/QsfGadnO+IFCIcPcE/EpChM48LLw2LdpCJQVZLEbXkrudVCq8jjjnK6MZQD1/3+CMBcP/uTgGzPPZ6FcbJv5WSvA2Y+E6gDXQ/x2qWl7PF6shx5y27RGPW8+tj+AUR+43e/jXE/1yyflnj4y6UbG7y0GdzVqRnvM+QX+BPfxBC+MXxR+F9pH85wnhZMDEVTgBsLwLEoRcediBCnhgAV1ULjxsbEAwtnrqdwg99DEJljTlHi8cabBbcNf7kHFJsJVhkwFcZBk/+ZFBedU78jdzouKelvfL4myt/OWq5kABdwdK6wJ/+BQK7D4ZJRFxn7nJESjXX9+U+ecFcr5KirsmIXiC6IX7Ck8s8GfWJPg2FfaGme4yhluPD+tVy1fpvpM4oJlbFJHR2k8AfsLbzpw2qDkC+BrDm9W/PKl/rABK+im1ZTaevfHvGwvJF259yufgKO4g7UkRi3rx5k0xvnmhLSd8/gxLzYCBoriN57yvrwFdTZqz412z0nC0+Mytag7RUKm9Io2PAhlbc0M/BySKucjvi3WYlfk/eAJ4wyqeQoWDH7nbYT/3nFREpNVn3VXQIIDZ6mmHE+Gld5A2SrNlOGqrZW7pF02eR9Dnr6fJoDM0WXqafvbaRfIXNilAp1C3rXEUum4IGECWRB6bHk3tpKYaekKdAiSKwUaOyPgpgtbf2KzKnL6I4v247FbGje0gF7t9Wseal+VTNDfH9Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: plex-secrets
      namespace: default