---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plex-secrets
  namespace: default
spec:
  encryptedData:
    PLEX_CLAIM: AgByOhjY7/Az3AwRTNBDOvbJxbsKHyuSHMMhaTpAm068Y7symHZUXxLeFuYKmCx1N1Wgw4p89ZbZfPrwAH/Pj9ts8RjRxoNWHPucNm71FiZsYoUxHWqUjxhoyTCAZ98RautJekxnbaAaACMKL7SeVFrPYcFyHEqQVEGaKW6omDYBAbLvuzr3w8Sc3PMFfwyWxnfdaNy6S+CTAM6pXnOtTtA3EhBS0ppl2D+0rHYsX5wH6ShEaxxyrhxth+ToXJHW2Rluobxg2UgEwnLI3smj1KK9J9Zos4CdPuPcM5meQykAfP73TKHSmqyUnRdOV7ExM/H5P20fGknu+rYdYl7QPEYHSeY4Mbsq5fWCSEOC3Y2LtE8vjp4/5w6THDuFHSg3vy58iuh13pwJGPIH/3vLCmjVzwdnqrWYvH9jPH1ay61Z78QTFE7Ra2EPxIrN5S4VMgQAApWpwpW/bD/Pc+9sqfmHlrxiqoUhFeIM/lomlz5sPAkBIz/OneS/lOKDLTTuNPyg6ZPbhoaNe4ZmQqiAQTb8j3erYGs/HKCv1QvOGG50r60YbbSmH4PdkGmSK0DPPPLegHGZXW0Eer+zIZAEvG0RodXSSkWV/vnsfbjLpxitZlhEHSlMVK/NJ1gLwqmVb6UNtL+t3GiyK6TCiZ7jMNanfIf+8Jka+7ATG3QjZ5aEQt3wwBAlQXn/gXrOb8MrrFcgRk86tUz44W8ik9lsWb1q4R0kgqwqOwJ3drI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: plex-secrets
      namespace: default