apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexconfig-pv
spec:
  storageClassName: synomounted
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: plexconfig-pvc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/plex/config"
  #nfs:
    #server: 10.10.10.105
    #path: "/volume1/Plex"