apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  releaseName: plex
  interval: 5m
  suspend: false
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    #image:
      #repository: ghcr.io/k8s-at-home/plex 
      #tag: v1.24.2.4973-2b1b51db9 
      #pullPolicy: IfNotPresent
    env:
      TZ: "America/Toronto"
      #PUID: 1000
      #PGID: 1000
    envFrom:
    - secretRef:
       name: plex-secret
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.10.10.201
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400
            targetPort: 32400
            protocol: TCP
    ingress:
      main:
        enabled: false
        #annotations:
          #kubernetes.io/ingress.class: "nginx"
          #external-dns.alpha.kubernetes.io/target: plex.tallflix.ca
        #hosts:
        #- host: plex.tallflix.ca
          #paths:
          #- path: /
            #pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: "/config"
        existingClaim: "plexconfig-pvc"
      transcode:
        enabled: true
        type: emptyDir
        #medium: Memory
      media:
        enabled: true
        mountPath: "/data/tvshows"
        existingClaim: tvshows-pvc
      media2:
        enabled: true
        mountPath: "/data/tvshows2"
        existingClaim: tvshows2-pvc
      media3:
        enabled: true
        mountPath: "/data/tvshows3"
        existingClaim: tvshows3-pvc
      media4:
        enabled: true
        mountPath: "/data/movies"
        existingClaim: movies-pvc
      media5:
        enabled: true
        mountPath: "/data/movies2"
        existingClaim: movies2-pvc
      media6:
        enabled: true
        mountPath: "/data/movies3"
        existingClaim: movies3-pvc
      media7:
        enabled: true
        mountPath: "/data/music"
        existingClaim: music-pvc
    #resources:
      #limits:
        #gpu.intel.com/i915: 1
        #memory: 4900Mi
      #requests:
        #gpu.intel.com/i915: 1
        #cpu: 763m
        #memory: 1500Mi