apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secret
  namespace: default
spec:
  encryptedData:
    PLEX_CLAIM: AgBO6OfP7QnP4lN4nHvLXzNZvYJNCrtqVr2nWLG5ouqAiPBg+/visZmMDg9cZbpIM4/WNlOjPE0wOqs1IDPiwGCvzAfyijC9Nk+DRZ9oE0zSDjg0bBlUgiDcKTAyDQwIQrkRN3/3Lw8QWVMl39tl3KaDNA0NxLoegZ20hlHDM7VdnFlFpPHhLDOiIFNd+6CMyciElRFyHqDcBpyDxUVNFZkzDW416J1idhx03smSeIE9fELdRk932jLTQuNDCyzP9hszU2Ychi96E/AXMc3RwRIywormvjMFJ+mpzur/j6bQyICPYKu/2XoYidF7kIjK+5uQ4R8eA0m+qRVjzBlmTmC5T+V96K80Lq4uWF9IGVFFW4RBkbwF+3rg+i3catfitnAO2ddEC3g3YNRH6ldY/LrjS/K593SET0DlYWXuwP2SkHRE3Z5lHdCf6C1AZ5aKTnFVvJvlFWmLntEpS9tBkt5azeyu3w67c0JU+/E0jnF+f6MuHoib+d5jlU9IWG8BJu2YBwCrOBn8wFBf2Ib/Ox3Ji/JHRlKTZodsPHJBAzy4uMxHova9fV6Rr2H6obFUM+I0M2a+JHxA6VnuZqHYpaNiNAqAcsuRwP0r0rbRoR892cP3UCoT1GSvcOcMEQ3XAwerFzsuHE4+QUDl0Fzru777ntesaoKPd5oJrznB/Rx9FhdesDwsNgYsL7oqSjYwlkh3KHX+vDjH8XIIaLund6JKlqwLWXwNzK23CA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: plex-secret
      namespace: default