apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-values
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgAVd00jcGqKtj3VmaYo2/swpL4iiuV7RQzSFGmC2dsYrGWDD3KZtdMlJtX68ZymsbeC8+ZhebzBqPkDXRmhAqLfYhKzgQqLBdQ7jBb77w+YCThhCcNm7qVPIDwNv8/TZCX8PKhongqGutTEMuXB+Fn14BMjyLB8nnEz12HPNqyyZqp8KCOXI1JhheOSEgWVbQBkwWkZdiuk4rb5VNkHCoxRMPGCMlIjiou4EYFenOaqYKFjfjUanDFxz+lUtDA+DyJtZS6BSX63nD1uA/2lnwmQny3QbIn7DuktuBReSDZEsbDexyfhlDr4BKP4vdyrvt2yxRK+nFNQ5M58qe/vIBnzByJX+bG588NkkyCPyblyqFYBeV3zjO846TwW//N5/47uTAPwZJFJg5MMIAtvvdBa5XpQj2FIXwSokWWMBd0Nr8IRbBT7GZfcuZMyw78nPnUz7AbtMovjAhf09ec5ZdrmUa7zDlmzS/ZHXADbXeu9hiX9+FERKmzqT3qR7JU00OMF+RvV1ShaHG4p5s7kFMwLsbzPmT5DlW2fUc9uPW6vvgcDtjRQa9c2veIDu+id7gY6pjW2ZwvtFblYjFhU7xQ7d577mq3SXA/xw6RiYr7M65DcHAuzIh8rvS/OOs3vqs2YVCt5dMneqUH6RH6DeyUCVAF2nJPC8eXZp4hT2WjInyyMuvstNCblMY6+UPS/7qGkj8oQ671kdbaWy0eeJmYvtW2JBnNSA5et8gxDHQS0JeA8N2ZwfV7oMQJrhDo8lb3t9CP00lMe1Az8ptTv+HGWsBk0x8NCC5jcq9SACFo+tu+AIrniamtp1WxOD1E7UCb1Z5LtXB9oVBY=
  template:
    metadata:
      creationTimestamp: null
      name: plex-values
      namespace: flux-system