apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexconfig-pv
spec:
  storageClassName: synomounted
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: plexconfig-pvc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/plexconfigbak"
  #nfs:
    #server: 10.10.10.105
    #path: "/volume1/Plex"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexconfig-pvc
  namespace: default
spec:
  storageClassName: synomounted
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvshows-pv
spec:
  storageClassName: thecusmounted
  capacity:
    storage: 8Ti
  claimRef:
    namespace: default
    name: tvshows-pvc
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/tvshows"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvshows-pvc
  namespace: default
spec:
  storageClassName: thecusmounted
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 8Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvshows2-pv
spec:
  storageClassName: synomounted
  capacity:
    storage: 5Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/media/tvshows2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvshows2-pvc
  namespace: default
spec:
  storageClassName: synomounted
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Ti
---