apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  #strategy:
  #  type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:5.0.1 # {"$imagepolicy": "flux-system:qbittorrent"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 6881
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America\Toronto
        - name: WEBUI_PORT
          value: "8080"
        - name: TORRENTING_PORT
          value: "6881"
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: sabnzbd-downloads-complete
          mountPath: /complete
        - name: sabnzbd-downloads-incomplete
          mountPath: /incomplete
      volumes:
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
      - name: sabnzbd-downloads-complete
        persistentVolumeClaim:
          claimName: downloads-complete-pvc
      - name: sabnzbd-downloads-incomplete
        persistentVolumeClaim:
          claimName: downloads-incomplete-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
  - name: qbittorrent
    port: 8080
    targetPort: 8080
  - name: qbittorrent-torrentudp
    port: 6881
    protocol: UDP
    targetPort: 6881
  - name: qbittorrent-torrenttcp
    port: 6881
    protocol: TCP
    targetPort: 6881
  type: ClusterIP