# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: qbittorrent
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: qbittorrent
#   #strategy:
#   #  type: Recreate
#   template:
#     metadata:
#       labels:
#         app: qbittorrent
#     spec:
      # containers:
      # - name: qbittorrent
      #   image: linuxserver/qbittorrent:14.3.9 # {"$imagepolicy": "flux-system:qbittorrent"}
      #   imagePullPolicy: IfNotPresent
      #   ports:
      #   - containerPort: 8080
      #   - containerPort: 6881
      #   env:
      #   - name: PGID
      #     value: "1000"
      #   - name: PUID
      #     value: "1000"
      #   - name: TZ
      #     value: America\Toronto
      #   - name: WEBUI_PORT
      #     value: "8080"
      #   - name: TORRENTING_PORT
      #     value: "6881"
      #   volumeMounts:
      #   - name: qbittorrent-config
      #     mountPath: /config
      #   - name: sabnzbd-downloads-complete
      #     mountPath: /complete
      #   - name: sabnzbd-downloads-incomplete
      #     mountPath: /incomplete
      # volumes:
      # - name: qbittorrent-config
      #   persistentVolumeClaim:
      #     claimName: qbittorrent-config-pvc
      # - name: sabnzbd-downloads-complete
      #   persistentVolumeClaim:
      #     claimName: downloads-complete-pvc
      # - name: sabnzbd-downloads-incomplete
      #   persistentVolumeClaim:
      #     claimName: downloads-incomplete-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: default
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
  - name: qbittorrent
    port: 8080
    targetPort: 8080
  - name: qbittorrent-torrentudp
    port: 6881
    protocol: UDP
    targetPort: 6881
  - name: qbittorrent-torrenttcp
    port: 6881
    protocol: TCP
    targetPort: 6881
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gluetun-deployment
    namespace: torrent
    labels:
        app: gluetun
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gluetun
    template:
        metadata:
            labels:
                app: gluetun
        spec:
            initContainers:
                - name: gluetun
                  # if you do not add restartPolicy the other init containers will never start
                  # it will be an initContainer and not a native sidecar container https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
                  restartPolicy: Always
                  image: ghcr.io/qdm12/gluetun
                  imagePullPolicy: Always
                  securityContext:
                      capabilities:
                          add:
                              - 'NET_ADMIN'
                  env:
                      - name: TZ
                        value: America\Toronto
                      - name: VPN_SERVICE_PROVIDER
                        value: nordvpn
                      - name: VPN_TYPE
                        value: openvpn
                      - name: SERVER_COUNTRIES
                        value: Netherlands
                      - name: OPENVPN_USER
                        value: USR
                      - name: OPENVPN_PASSWORD
                        value: PWD
                - name: curlpodtest
                  image: curlimages/curl
                  command: ['/bin/sh', '-c']
                  args:
                      - &check-ip |
                          IP=$(curl -s checkip.amazonaws.com)
                          EXPECTED_IP="YOUR_IP_ADDRESS"
                          if [ "$IP" != "$EXPECTED_IP" ]; then
                            echo "IP is different from $EXPECTED_IP. Current IP is $IP."
                          else
                            echo "IP is $EXPECTED_IP. Exiting..."
                            exit 1
                          fi
            containers:
            - name: qbittorrent
              image: linuxserver/qbittorrent:14.3.9 # {"$imagepolicy": "flux-system:qbittorrent"}
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 8080
              - containerPort: 6881
              env:
              - name: PGID
                value: "1000"
              - name: PUID
                value: "1000"
              - name: TZ
                value: America\Toronto
              - name: WEBUI_PORT
                value: "8080"
              - name: TORRENTING_PORT
                value: "6881"
              volumeMounts:
              - name: qbittorrent-config
                mountPath: /config
              - name: sabnzbd-downloads-complete
                mountPath: /complete
              - name: sabnzbd-downloads-incomplete
                mountPath: /incomplete
            volumes:
            - name: qbittorrent-config
              persistentVolumeClaim:
                claimName: qbittorrent-config-pvc
            - name: sabnzbd-downloads-complete
              persistentVolumeClaim:
                claimName: downloads-complete-pvc
            - name: sabnzbd-downloads-incomplete
              persistentVolumeClaim:
                claimName: downloads-incomplete-pvc