apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-secret
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgA4n5hHO7PWg3VOIjREdOEe8w86gy9/HGSY3LFsbRX+kF0vXk3RKNyA/RU7VhhF70GAzYAEfnJlEmEU+nvftj4oP0lNn5DOtKqbFuDowUrZfVQsQTDVQgwTi5EDVwfgGlnzuDnfqgvZvrDOH4BXltXqu93UPMRiyNi+XfLAUar4WhLuCgBgBGG3oNdM9cg1widhMEsqkPS3gbC0hbbykUQHnzG5lpA2bQBR/jzrU44jQekI/LZmoyn+njhONfG4Z8TqoRHIcRkdBIn/v1yc8ncI9uVPXWy8JJS2FCYZ1seq3CLkarTEQEZjUKBEF0CGRCTVlnqCmORqLimLA2fYVrz6W4DZG+d/o8X9O3k1RMCEeK5U+eOX3pG5nJd/Aspccbg/scUGqlIJ2iKz3i2KwbClPK8E+8S8wPJbtOgeE+5byk2PrBFvabHSxGl+SofhF9Y4Bf3JaByvKcxdn3BdFKjYwAW+soiKvm7EFX/cBKBLK4nE6YSL1+rT3X2wNzLM8Pk459TMMb6hPBMx6Ttahx/bGuEmJcoB6PZoNoQ0LBV2Lwc3pVSxSXe/kq3NmF92KPKMZqEWhve3Mu4iBJtULKmxGeIzIIR8ne+MFZU3JyyZO9wshjabGN39tRhX3xCfVzs4j8CtGue/Fv1IANrcykfiA3KfCMhL50O/JVkTfN0phL6DfpSKOfNT9FtnGxeZepChsrQz9IN/gLSynJUXxPckZfNIZXX5ZH+Cnjgm8MsU4WrlxcZGlzRfW74w
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nginx-secret
      namespace: longhorn-system
    type: Opaque