apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      #version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.5.55 # {"$imagepolicy": "flux-system:unifi:tag"}
    env:
      TZ: "America/Toronto"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.10.10.62
        externalTrafficPolicy: Local
        ports:
          devicecomm:
            port: 8080
            targetPort: 8080
            protocol: TCP
          webadmin:
            port: 8443
            targetPort: 8443
            protocol: TCP
          mobilethroughputtest:
            port: 6789
            targetPort: 6789
            protocol: TCP
      mainudp:
        type: LoadBalancer
        loadBalancerIP: 10.10.10.62
        externalTrafficPolicy: Local
        ports:
          stun:
            port: 3478
            targetPort: 3478
            protocol: UDP
          discovery:
            port: 10001
            targetPort: 10001
            protocol: UDP
    ingress:
      main:
        enabled: false
    persistence:
      data:
        enabled: true
        existingClaim: unifi-config-pvc
