apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: default
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app.kubernetes.io/instance: plex
      app.kubernetes.io/name: plex
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: plex
        app.kubernetes.io/name: plex
    spec:
      containers:
      - env:
        - name: ADVERTISE_IP
          value: http://10.10.10.61:32400/
        - name: ALLOWED_NETWORKS
          value: 10.10.10.0/24
        - name: TZ
          value: America/Toronto
        envFrom:
        - secretRef:
            name: plex-secret
        image: plexinc/pms-docker:1.43.0.10467-2b1ba6e69-amd64 # {"$imagepolicy": "flux-system:plex"}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 1
        name: plex
        ports:
        - containerPort: 32400
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 2Gi
            gpu.intel.com/i915: "1"
          limits:
            cpu: "4"
            memory: 8Gi
            gpu.intel.com/i915: "1"
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data/tvshows
          name: tv1
        - mountPath: /data/tvshows3
          name: tv3
        - mountPath: /data/music
          name: music
        - mountPath: /data/movies3
          name: movies
        - mountPath: /data/ytshows
          name: yt
        - mountPath: /transcode
          name: transcode
      securityContext:
        supplementalGroups:
        - 44
        - 107
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config-pvc
      - name: tv1
        persistentVolumeClaim:
          claimName: tvshows-pvc
      - name: tv3
        persistentVolumeClaim:
          claimName: tvshows3-pvc
      - name: yt
        persistentVolumeClaim:
          claimName: ytshows-pvc
      - name: music
        persistentVolumeClaim:
          claimName: music-pvc
      - name: movies
        persistentVolumeClaim:
          claimName: movies3-pvc
      - emptyDir: {}
        name: transcode
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: plex
    metallb.universe.tf/ip-allocated-from-pool: myipaddresspool
  name: plex
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.10.10.61
  ports:
  - name: http
    nodePort: 32534
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
  type: LoadBalancer
