---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
  interval: 10m0s
  releaseName: node-feature-discovery
  targetNamespace: node-feature-discovery