---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  suspend: false
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: bitnami-labs-charts
        namespace: flux-system
  install:
    crds: Create

  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace