---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret
  namespace: default
spec:
  encryptedData:
    password: AgBjWj4gCJt0qkiZlps/ccDiA3JxWPrUtDoPwZih6nXuUsq3Wr2MfnZ4D7etfNnxu70pv3lLdU6KUCbCP7Muw4/gPd9Sd+iwxMIEuEY40ipEHtAtn3G1ehRRfNP1lBKSM1tnW/Aq9v06T5fEGcUcAFgp4RTZjiTXr0yFQFRzm2ixw3MAg4XXTtY/yIEv76SsoLhSjpfDw6jbp0oGmTwmx9qFxgHjJuT7z+W184QZl26eZJeboDT5tWcAv0lbyUxD+6oyyn3KIqZWnVNOippNVX+GH60LzX0YMh0UX97/Kprxd8Eu+sGVBQkLpivZslaOzlU/mi+L5CLRWylTg2YWqT2SLVVBFvnHAkEiraL0pK5q6vFGqHgUbXZx/oa5Pxnb08VQJY2iXpYKMLLSqoB7kYnLga7UO/ZeTRi6ZEIdkDesS0ugVL7xfTV9jKRB4581pd52KX20LSCRC0LfI8ObINBs3l2SBN2cMT9BIwwcR07uIgsUxwyfLEiIZ7B3DWpqF/ffP5rqw8kZHP/FpA1k4ijEf8Bfj6SQt74cBkLJosFd8m6I3GwUD0s+4uonQK+bJ3uZj9zJwLZRjomkCYjAyZrKWYCqgTZaXPBnvNKFR44tbBik2ZdSqz1zyIpU9Mn/JNjxkYGC9BQVwWAZ2XXUgTIghzd2OQFNuRx08yQFU8OOwncAeqs7lXbuRMy7OsGLuvX2R3xHls348QIOSJ5Q1w==
    postgres-password: AgBTXza2q+slpbOrreRw3rI5c6ZvnQyBoa0raUr45vwcrEueDsaFuTjxc/N0FXwAkdO3Sa7NH1oZC4aShDeRy6SrfY1RplqxVYx/Ad4jOuP45ap6qSS0uj6Cw1bhWf5vvAdKtVqmxk+d+ZW3HxoiLDfT3F24y8QCQ+vQHMWalqEp4MsTlE0OeYVHB4ExkbR40rgc5niwSponRubeAfAM9eIfzIj87zcHRcfACOiWIq3oNJvJAqINMzyiUVdzGbytHa4IE/dd9vsGmAa511liTQ8AOREWOFYIy2D+CSx5i9d9n5+F1jGnLTPmeZp8kuTjPh/HOXVyaVWIkxdhkvPS/o2JHXld5G7xGQCN3NOEHf4M+iVz8k1GTLRboktPpImk+nH9VXZdwsn5pQUZSlh8Q7OWFW4i3M7WgjMMBISlmykYptRFQdO13/ccNqna/JaACz+u6XCZ26wb4dM/QwNVrarWdtutTZyVZYGw6XXR+IjWNJ+b05/C94um9cRnpWamwuKXQsCZNyiAX1cqOuek/BvYnme+BrbcF+JoJ2aAM8Xp/OrdgHxBGTtHoyv6gmIS5Q76Eriyd0I6IeQQnwDK7CRTesegJnuo2lZcp54FzrliW+UC78/h7Mm1nU4XuNvJr2oIllOj9Wl392kYu6sR1L8RJhZNGSSdECjpxYeWjH9HeUwB/HLP+aiwiec/tNu0wPS3veDjFMgrI3dBOZseWw==
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret
      namespace: default