apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: immich-redis
spec:
  replicas: 1
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      containers:
        - name: immich-redis
          image: docker.io/redis:8.6.0-alpine # {"$imagepolicy": "flux-system:redis"}
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 5m
              memory: 8Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: default
spec:
  selector:
    app: immich-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
