---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  DOMAIN: tallflix.ca
  METALLB_ADDR_RANGE: 10.10.10.201-10.10.10.205
  PLEX_LB: 10.10.10.201
  HOME_ASSISTANT_LB: 10.10.10.202
  UNIFI_LB: 10.10.10.203
