apiVersion: v1
kind: PersistentVolume
metadata:
  name: unificonfig-pv3
spec:
  storageClassName: syno-nfs
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: 10.10.10.105
    path: "/volume1/K8sConfig/unifi"
