apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    type: longhorn
    app: example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi