---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi-longhorn
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      #      nodeSelector:
      #        fileserv: "true"
      containers:
        - name: ombi
          image: linuxserver/ombi:4.7.10 # {"$imagepolicy": "flux-system:ombi"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3579
          env:
            - name: TZ
              value: America\Toronto
          volumeMounts:
            - name: ombi-config
              mountPath: /config
      volumes:
        - name: ombi-config
          persistentVolumeClaim:
            claimName: ombi-config-pvc2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config-pvc2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: ombi-config-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-config-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '2880'
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: ombi-config-pv1
#spec:
  #storageClassName: synomounted
  ##capacity:
  #  storage: 8Ti
  #claimRef:
  #  namespace: default
  #  name: ombi-config-pv1
  #accessModes:
  #  - ReadOnlyMany
  #persistentVolumeReclaimPolicy: Retain
  #hostPath:
 #   path: "/media/ombi/config/"
---