---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: plex
  namespace: default
spec:
  interval: 1h0m0s
  url: https://github.com/k8s-at-home/charts/blob/master/charts/stable/plex/Chart.yaml