---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://raw.githubusercontent.com/k8s-at-home/charts/master/charts/stable/plex/Chart.yaml