---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: flux-system
spec:
  chart:
    spec:
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: plex
      version: '>=6.0.0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: plex
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace