apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
#    kubernetes.io/name: "sonarr"
spec:
  selector:
    app: sonarr
  ports:
  - name: sonarr
    port: 8989
    targetPort: 8989
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
#    kubernetes.io/name: "radarr"
spec:
  selector:
    app: radarr
  ports:
  - name: radarr
    port: 7878
    targetPort: 7878
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ombi
  labels:
    app: ombi
#    kubernetes.io/name: "radarr"
spec:
  selector:
    app: ombi
  ports:
  - name: ombi
    port: 3579
    targetPort: 3579
  type: ClusterIP