apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  selector:
    app: sonarr
  ports:
  - name: sonarr
    port: 8989
    targetPort: 8989
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  selector:
    app: radarr
  ports:
  - name: radarr
    port: 7878
    targetPort: 7878
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ombi
  labels:
    app: ombi
spec:
  selector:
    app: ombi
  ports:
  - name: ombi
    port: 3579
    targetPort: 3579
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    app: tautulli
spec:
  selector:
    app: tautulli
  ports:
  - name: tautulli
    port: 8181
    targetPort: 8181
  type: ClusterIP