---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
        app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
#      nodeSelector:
#        fileserv: "true"
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        imagePullPolicy: Always
        ports:
        - containerPort: 8989
        env:
        - name: PGID
          value: "1001"
        - name: PUID
          value: "1001"
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - name: sonarr-config
          mountPath: /config
        - name: sonarr-configxml-volume
          mountPath: /config/config2.xml
          subPath: config2.xml
        - name: sonarr-tv
          mountPath: /tv
        - name: sonarr-tv2
          mountPath: /tv2
          #mountPropagation: Bidirectional       
        - name: sonarr-tv3
          mountPath: /tv3
          #mountPropagation: Bidirectional
        - name: sonarr-downloads
          mountPath: /downloads
      volumes:
      - name: sonarr-config
        hostPath:
          path: /media/sonarr/config/
      - name: sonarr-configxml-volume
        configMap:
          name: sonarr-configxml
          items:
           - key: config2.xml
             path: config2.xml
      - name: sonarr-tv
        hostPath:
          path: /media/tvshows
      - name: sonarr-tv2
        hostPath:
          path: /media/tvshows2
      - name: sonarr-tv3
        hostPath:
          path: /media/tvshows3
      - name: sonarr-downloads
        hostPath:
          path: /media/complete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
        app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
#      nodeSelector:
#        fileserv: "true"
      containers:
      - name: radarr
        image: linuxserver/radarr
        imagePullPolicy: Always
        ports:
        - containerPort: 7878
        env:
        - name: PGID
          value: "1001"
        - name: PUID
          value: "1001"
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - name: radarr-config
          mountPath: /config
        - name: radarr-movies
          mountPath: /movies
        - name: radarr-movies2
          mountPath: /movies2
          #mountPropagation: Bidirectional       
        - name: radarr-movies3
          mountPath: /movies3
          #mountPropagation: Bidirectional
        - name: radarr-downloads
          mountPath: /downloads
      volumes:
      - name: radarr-config
        hostPath:
          path: /media/radarr/config/
      - name: radarr-movies
        hostPath:
          path: /media/movies
      - name: radarr-movies2
        hostPath:
          path: /media/movies2
      - name: radarr-movies3
        hostPath:
          path: /media/movies3
      - name: radarr-downloads
        hostPath:
          path: /media/complete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
spec:
  replicas: 1
  selector:
    matchLabels:
        app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
#      nodeSelector:
#        fileserv: "true"
      containers:
      - name: ombi
        image: linuxserver/ombi
        imagePullPolicy: Always
        ports:
        - containerPort: 3579
        env:
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - name: ombi-config
          mountPath: /config
      volumes:
      - name: ombi-config