apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyzebridge
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wyzebridge
    strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: wyzebridge
    spec:
      hostname: wyzebridge
      containers:
      - name: wyzebridge
        image: mrlt8/wyze-bridge:2.3.14 # {"$imagepolicy": "flux-system:wyzebridge"}
        imagePullPolicy: IfNotPresent
        type: ClusterIP
        ports:
        - containerPort: 1935
        - containerPort: 8554
        - containerPort: 8888
        - containerPort: 5000
        env:
        - name: TZ
          value: America\Toronto
        - name: ENABLE_AUDIO
          value: 'true'
        envFrom:
        - secretRef:
            name: wyzebridge-secret
        volumeMounts:
        - name: wyzebridge-config
          mountPath: /tokens
      volumes:
      - name: wyzebridge-config
        persistentVolumeClaim:
          claimName: wyzebridge-config-pvc
