---
# 1. WEBSERVER - Handles HTTP requests only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-webserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-webserver
  template:
    metadata:
      labels:
        app: paperless-webserver
    spec:
      containers:
        - name: paperless-webserver
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.3
          ports:
            - containerPort: 8000
          env:
            - name: PAPERLESS_REDIS
              value: redis://paperless-redis:6379
            - name: PAPERLESS_DBHOST
              value: paperless-postgresql
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: db-user
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: db-pass
            - name: PAPERLESS_DBNAME
              value: paperless
            - name: PAPERLESS_URL
              value: https://paperless.tallflix.ca
            - name: PAPERLESS_TIME_ZONE
              value: America/Toronto
            - name: PAPERLESS_OCR_LANGUAGE
              value: eng
            - name: PAPERLESS_ENABLE_ALLAUTH
              value: "true"
            - name: PAPERLESS_APPS
              value: "allauth.socialaccount.providers.openid_connect"
            - name: PAPERLESS_SOCIALACCOUNT_PROVIDERS
              valueFrom:
                secretKeyRef:
                  name: paperless-socialaccount
                  key: PAPERLESS_SOCIALACCOUNT_PROVIDERS
            - name: PAPERLESS_REDIRECT_LOGIN_TO_SSO
              value: "true"
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: secret-key
            - name: PAPERLESS_TIKA_ENABLED
              value: "true"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://paperless-gotenberg:3000
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://paperless-tika:9998
            # Disable worker and consumer in webserver
            - name: PAPERLESS_WEBSERVER_WORKERS
              value: "2"
          volumeMounts:
            - name: paperless-data
              mountPath: /usr/src/paperless/data
            - name: paperless-media
              mountPath: /usr/src/paperless/media
            - name: paperless-export
              mountPath: /usr/src/paperless/export
            # Use emptyDir for logs to avoid NFS lock issues
            - name: logs
              mountPath: /usr/src/paperless/log
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data-pvc
        - name: paperless-media
          persistentVolumeClaim:
            claimName: paperless-media-pvc
        - name: paperless-export
          persistentVolumeClaim:
            claimName: paperless-export-pvc
        - name: logs
          emptyDir: {}

---
# 2. WORKER - Processes documents (can scale)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-worker
  namespace: default
spec:
  replicas: 1  # Can increase if needed
  selector:
    matchLabels:
      app: paperless-worker
  template:
    metadata:
      labels:
        app: paperless-worker
    spec:
      containers:
        - name: paperless-worker
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.3
          command: ["/usr/local/bin/paperless-worker"]
          env:
            - name: PAPERLESS_REDIS
              value: redis://paperless-redis:6379
            - name: PAPERLESS_DBHOST
              value: paperless-postgresql
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: db-user
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: db-pass
            - name: PAPERLESS_DBNAME
              value: paperless
            - name: PAPERLESS_TIME_ZONE
              value: America/Toronto
            - name: PAPERLESS_OCR_LANGUAGE
              value: eng
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: secret-key
            - name: PAPERLESS_TIKA_ENABLED
              value: "true"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://paperless-gotenberg:3000
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://paperless-tika:9998
            # Mobile upload timeout fixes
            - name: PAPERLESS_WORKER_TIMEOUT
              value: "3600"
            - name: PAPERLESS_OCR_IMAGE_DPI
              value: "300"
            - name: PAPERLESS_OCR_ROTATE_PAGES
              value: "false"
            - name: PAPERLESS_OCR_DESKEW
              value: "false"
            - name: PAPERLESS_TASK_WORKERS
              value: "1"
            - name: PAPERLESS_THREADS_PER_WORKER
              value: "1"
          volumeMounts:
            - name: paperless-data
              mountPath: /usr/src/paperless/data
            - name: paperless-media
              mountPath: /usr/src/paperless/media
            - name: paperless-export
              mountPath: /usr/src/paperless/export
            - name: logs
              mountPath: /usr/src/paperless/log
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data-pvc
        - name: paperless-media
          persistentVolumeClaim:
            claimName: paperless-media-pvc
        - name: paperless-export
          persistentVolumeClaim:
            claimName: paperless-export-pvc
        - name: logs
          emptyDir: {}

---
# 3. BEAT - Scheduler (MUST be exactly 1 replica)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-beat
  namespace: default
spec:
  replicas: 1  # CRITICAL: Must be exactly 1
  selector:
    matchLabels:
      app: paperless-beat
  template:
    metadata:
      labels:
        app: paperless-beat
    spec:
      containers:
        - name: paperless-beat
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.3
          command: ["/usr/local/bin/paperless-beat"]
          env:
            - name: PAPERLESS_REDIS
              value: redis://paperless-redis:6379
            - name: PAPERLESS_DBHOST
              value: paperless-postgresql
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: db-user
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: db-pass
            - name: PAPERLESS_DBNAME
              value: paperless
            - name: PAPERLESS_TIME_ZONE
              value: America/Toronto
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secret
                  key: secret-key
          volumeMounts:
            # Beat schedule on emptyDir to avoid NFS lock issues
            - name: beat-schedule
              mountPath: /usr/src/paperless/data
            - name: logs
              mountPath: /usr/src/paperless/log
      volumes:
        - name: beat-schedule
          emptyDir: {}
        - name: logs
          emptyDir: {}

---
# Update Service to point to webserver
apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  namespace: default
spec:
  selector:
    app: paperless-webserver  # Changed from paperless-ngx
  ports:
    - port: 8000
      targetPort: 8000