---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      #backupTarget: s3://longhorn@minio/backups
      #backupTargetCredentialSecret: longhorn-backup
      defaultReplicaCount: 2
      #defaultLonghornStaticStorageClass: longhorn
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: longhorn
        hosts:
        - host: longhorn.tallflix.ca
          paths:
          - path: /
            pathType: Prefix
            #backend:
            #  service:
            #    name: longhorn
            #    port:
            #      number: 8123
        tls:
        - hosts:
          - longhorn.tallflix.ca
          secretName: tls-secret