apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-secret
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgATHN1P98dOZF1MCECBXyAK2uSo8ZCTP54ib3pxI8Hxnc+hIqlsR5uYdb33sxw6Kzi/Ry3KTW7FldKqDZEo5VLy8zX/lwmmoEh4ZBJ2/GnyH3tFCBBFU24HzNxq0F8L/ZcjT3k+YHlzjY62cfnlRK/r+ajoiWOLgvXkB9gZEUW41C0xQclf6N70cyaYgVUPgw3hwyUuvDoI9CEAXoV1ngqVmx0pYHcIgny/FWXj1lNUiOFX/+6xirDpD6YtgIXkBlilQdhtZK4vrPBlef1jtKp6usf8P+pDvHYkTevi6OBrFInQ3+6SuPXodvjRFmxrl1m11T4n9I/xbkcs/wIGDjcR2aAInO7NoevZM8ocsfffWkwfd9wdhg7wJz3Oeu67W3KpKPr2vZdLMlCePYEVPue/PpzZt+0jgYd9m11lERdus8oT3CCFAFParc4F0PxtfSnSo7YHXMwKrJFWlaDcBvO9dq8kU7RxIeOVebytyr/wba5+NI3NIxtCZV87E8/NQigbUFaBJ6wIJn7Qxbb9TOp5+2Qlw7GrF0Q+iDvQztJfN/xop4ga2o1M2kqc4/p4QMhfB9Qjp4K474aXx/N9k0U7s65UBo8yWLJnPSrclQvY5jSJzsPmFYitfIP0cTbeMFMZgGeuFA/qTRzB2ZsEafIh2SStS1BvAyVwMIx8le00uWAuUkxrEH+Ue6Nh/oNX2ajGhfb7OwhvnmpSD3oT5kKCs75Ts7PXWcZd3JM4Irg1CZE+jeLWbYLstTx5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nginx-secret
      namespace: longhorn-system
    type: Opaque