apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  releaseName: plex
  interval: 5m
  suspend: false
  chart:
    spec:
      chart: plex
      #version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.27.1.5916-6b0e31a64 # {"$imagepolicy": "flux-system:plex:tag"}
    env:
      TZ: "America/Toronto"
    envFrom:
    - secretRef:
        name: plex-secret
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      # Hardware acceleration using an Intel iGPU w/ QuickSync
      # These IDs below should be matched to your `video` and `render` group on the host
      # To obtain those IDs run the following grep statement on the host:
      # $ cat /etc/group | grep "video\|render"
      # video:x:44:
      # render:x:109:
      supplementalGroups:
      - 44
      - 109
    resources:
      requests:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        gpu.intel.com/i915: 1
        cpu: 200m
        memory: 256Mi
      limits:
        #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
        #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        gpu.intel.com/i915: 1
        memory: 4096Mi
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.10.10.61
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400
            targetPort: 32400
            protocol: TCP
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        mountPath: "/config"
        existingClaim: "plex-config-pvc"
      transcode:
        enabled: true
        type: emptyDir
        #medium: Memory
      media:
        enabled: true
        mountPath: "/data/tvshows"
        existingClaim: tvshows-pvc
      #media2:
      #enabled: true
      #mountPath: "/data/tvshows2"
      #existingClaim: tvshows2-pvc
      media3:
        enabled: true
        mountPath: "/data/tvshows3"
        existingClaim: tvshows3-pvc
      #media4:
      #enabled: true
      #mountPath: "/data/movies"
      #existingClaim: movies-pvc
      #media5:
      #enabled: true
      #mountPath: "/data/movies2"
      #existingClaim: movies2-pvc
      media6:
        enabled: true
        mountPath: "/data/movies3"
        existingClaim: movies3-pvc
      media7:
        enabled: true
        mountPath: "/data/music"
        existingClaim: music-pvc
