apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-secret
  namespace: default
spec:
  encryptedData:
    PLEX_CLAIM: AgC4eyOSA6/Fk4KJoB3m48ZVnkpc3pTH7+1jrCVXGGYivtD2xd9ssREFyMONdzk9wecH17JL/KHgFjJ5YUl0vn1KqV9C911sUbqn8XVGpNO0yKx3gmcLDrOT9lGhTdwK5GKf2xkRiBnVvsFm57MRr0GKrLNv0lLKCaqxyonFq4hN4W0an3eanROk9d+LSr0Vz+Bc1ZzyZvv+IvWP7Pcwd9qFHKktVqI4i+mZKL9gaxmdGQKXkaePxhuF3mQV/EjzZrrpYvDWZx23B2E22bXsokm21S+GnxnERVNDu41OjliNcqafdRPWysB7gVDkqFZ+KCdp/iIEOjQdqqAxfSHWE4MfoUxipvxr7nzlQKUOeJp4HRio5cqs2cbAZrrp/SiI9FB1T/AE4wtDuEDhEBvLQuNT76bqA3vc0mlBazdeWh8ci1a9vQ3yA1hZ0UgjSvpCTJwPlUDhpI2wYpdM7SdnlPPwhUJOPnX+4VhPYHBWWFyYpSgKq5kJQHNXebYz0uxo/lUlU73zc3Jk7yTCanQU2dGAmF+CVCRCq0PRSBpW2Ev+SP4tRLdp24BgzYiMr5iAjHg7vCICXHSwHnlPrcSG4XJiB0pww8XtOsBnuvklwc1wzAnzmXPN770xUe5G/5rAm9jG+xaqUzNTEhrjUIz2myAe9wwPh99aKREHjRSn7//rz1qErFx41DUW4al4WmHTaDqJU0JkC/Z5q1/x1/MymKdyuSq+REgNPYy65Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: plex-secret
      namespace: default