---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 11.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.12.1
    env:
      TZ: America/Toronto
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.10.10.203
        externalTrafficPolicy: Local
    securityContext:
      privileged: true
    # -- Enable devices to be discoverable
    hostNetwork: true
    
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: home-assistant
        hosts:
        - host: hass.tallflix.ca
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
        tls:
        - hosts:
          - hass.tallflix.ca
          secretName: tls-secret

    persistence:
      config:
        enabled: true
        existingClaim: homeassistantconfig-pvc