apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: home-assistant
      app.kubernetes.io/name: home-assistant
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: home-assistant
        app.kubernetes.io/name: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:2026.4.4 # {"$imagepolicy": "flux-system:homeassistant"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: America/Toronto
        resources:
          requests:
            cpu: 250m
            memory: 384Mi
          limits:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - mountPath: /config
          name: config
        securityContext:
          privileged: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: default
  annotations:
    lbipam.cilium.io/ips: 10.10.10.63
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    protocol: TCP
    port: 8123
    targetPort: 8123
  selector:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
  type: LoadBalancer