apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: music-assistant
  labels:
    app: music-assistant
spec:
  replicas: 1
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: music-assistant
      app.kubernetes.io/name: music-assistant
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: music-assistant
        app.kubernetes.io/name: music-assistant
    spec:
      containers:
      - name: music-assistant
        image: ghcr.io/music-assistant/server:2.4.3
         # {"$imagepolicy": "flux-system:musicassistant"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8095
        - containerPort: 8098
        env:
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - mountPath: /data
          name: config
        securityContext:
          # privileged: true
          capabilities:
            add: 
             - SYS_ADMIN
             - DAC_READ_SEARCH
      hostNetwork: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: musicassistant-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: music-assistant
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.10.10.69
  ports:
  - name: http
    protocol: TCP
    port: 8095
    targetPort: 8095
  - name: streamserver
    protocol: TCP
    port: 8098
    targetPort: 8098
  selector:
    app.kubernetes.io/instance: music-assistant
    app.kubernetes.io/name: music-assistant
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: music-assistant
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/server-snippets: |
      location /api/websocket {
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
  labels:
    app.kubernetes.io/name: music
  name: music-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: music.tallflix.ca
    http:
      paths:
      - backend:
          service:
            name: music-assistant
            port:
              number: 8095
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - music.tallflix.ca
    secretName: music-secret
status:
  loadBalancer:
    ingress:
    - ip: 10.10.10.69