apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: music-assistant
  labels:
    app: music-assistant
spec:
  replicas: 1
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: music-assistant
      app.kubernetes.io/name: music-assistant
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: music-assistant
        app.kubernetes.io/name: music-assistant
    spec:
      containers:
      - name: music-assistant
        image: ghcr.io/music-assistant/server:2.4.3
         # {"$imagepolicy": "flux-system:musicassistant"}
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America\Toronto
        volumeMounts:
        - mountPath: /data
          name: config
        securityContext:
          # privileged: true
          capabilities:
            add: 
             - SYS_ADMIN
             - DAC_READ_SEARCH
      hostNetwork: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: musicassistant-config-pvc