apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-skyblockisland
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-skyblockisland
  template:
    metadata:
      labels:
        app: minecraft-skyblockisland
        podtype: minecraft
    spec:
      hostNetwork: true
      extraPodSpec:
        hostNetwork: "{{ .Values.hostNetwork }}"
      containers:
      - name: minecraft-skyblockisland
        image: itzg/minecraft-bedrock-server:2025.6.0 # {"$imagepolicy": "flux-system:minecraft"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 19132
          protocol: UDP
        env:
        - name: TZ
          value: America\Toronto
        - name: SERVER_NAME
          value: "Finn and Kane"
        - name: LEVEL_NAME
          value: "SkyblockIsland"
        - name: ENABLE_LAN_VISIBILITY
          value: "true"
        - name: GAMEMODE
          value: "creative"
        - name: EULA
          value: "true"
        - name: ALLOW_CHEATS
          value: "true"
        - name: OPS
          value: "2533274835894189"
        - name: ENABLE_COMMAND_BLOCK
          value: "true"
        - name: DIFFICULTY
          value: "easy"
        - name: ONLINE_MODE
          value: "true"
        - name: SERVER_PORT
          value: "19132"
        volumeMounts:
        - name: minecraft-config-skyblockisland
          mountPath: /data
      volumes:
      - name: minecraft-config-skyblockisland
        persistentVolumeClaim:
          claimName: minecraft-skyblockisland-config-pvc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

##Installing data:

## Download from https://www.curseforge.com/minecraft-bedrock/maps or https://www.planetminecraft.com/project/
##  This one is https://www.planetminecraft.com/project/skyblock-evolved-lots-of-different-islands-1-21-bedrock-edition/
##  kubectl cp '/mnt/c/Users//Downloads/skyblock-evolved.mcworld'  minecraft-SKYBLOCKISLAND-66c48947fd-5tq5w:/data/
##  unzip skyblock-evolved.mcworld in the worlds folder
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-skyblockisland
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.10.10.75
  ports:
  - name: minecraft-skyblockisland
    port: 19132
    protocol: UDP
    targetPort: 19132
  selector:
    app.kubernetes.io/instance: minecraft-skyblockisland
    app.kubernetes.io/name: minecraft-skyblockisland
  type: LoadBalancer
