apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      hostNetwork: true
      containers:
      - name: minecraft
        image: itzg/minecraft-bedrock-server:5.18.4 2024.11.0 # {"$imagepolicy": "flux-system:minecraft"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 19132
        env:
        - name: TZ
          value: America\Toronto
        - name: SERVER_NAME
          value: "McBrideServer"
        - name: ENABLE_LAN_VISIBILITY
          value: "TRUE"
        - name: EULA
          value: "TRUE"
        - name: ALLOW_CHEATS
          value: "TRUE"
        - name: DIFFICULTY
          value: "easy"
        - name: ONLINE_MODE
          value: "TRUE"
        - name: SERVER_PORT
          value: "19132"
        volumeMounts:
        - name: minecraft-config
          mountPath: /data
      volumes:
      - name: minecraft-config
        persistentVolumeClaim:
          claimName: minecraft-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.10.10.69
  ports:
  - name: minecraft
    port: 19132
    protocol: UDP
    targetPort: 19132
  selector:
    app.kubernetes.io/instance: minecraft
    app.kubernetes.io/name: minecraft
  type: LoadBalancer