apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: default
spec:
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Toronto
        image: v8.6.9 # {"$imagepolicy": "flux-system:unifi:tag"}
        imagePullPolicy: IfNotPresent
        name: unifi
        ports:
        - containerPort: 8080
          name: controller
          protocol: TCP
        - containerPort: 8443
          name: http
          protocol: TCP
        - containerPort: 6789
          name: speedtest
          protocol: TCP
        - containerPort: 3478
          name: stun
          protocol: UDP
        - containerPort: 10001
          name: discovery
          protocol: UDP
        volumeMounts:
        - mountPath: /unifi
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: unifi-config-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: unifi # < name of the service
  namespace: default # < namespace where to place service
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: myipaddresspool
spec:
  ports:
  - port: 8080 # < port to open on the outside on the server
    targetPort: 8080 # < targetport. port on the pod to passthrough
    name: controller # < reference name for the port in the deployment yaml
    protocol: TCP
  - port: 8443 # < port to open on the outside on the server
    targetPort: 8443 # < targetport. port on the pod to passthrough
    name: http # < reference name for the port in the deployment yaml
    protocol: TCP
  - port: 6789 # < port to open on the outside on the server
    targetPort: 6789 # < targetport. port on the pod to passthrough
    name: speedtest # < reference name for the port in the deployment yaml
    protocol: TCP
  - port: 3478
    targetPort: 3478
    name: stun
    protocol: UDP
  - port: 10001
    targetPort: 10001
    name: discovery
    protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 10.10.10.62
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-ingress
  namespace: default
spec:
  ingressClassName: internal-nginx
  #tls:
  #- hosts:
  #  - "unifi.tallflix.ca"
  #  secretName: tls-secret
  rules:
  - host: unifi.tallflix.ca
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: unifi
            port:
              number: 8443
