---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unificonfig-pvc1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: syno-nfs
  volumeName: unificonfig-pv1
  resources:
    requests:
      storage: 500Mi