apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  strategy:
  type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Toronto
        image: 2.0.18 # {"$imagepolicy": "flux-system:eclipse-mosquitto:tag"}
        imagePullPolicy: IfNotPresent
        name: mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: default
spec:
  loadBalancerIP: 10.10.10.64
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app.kubernetes.io/name: mosquitto
  type: LoadBalancer
