---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    crds: Create
  interval: 30m0s
  releaseName: metallb
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
  values:
    configInline:
      address-pools:
      - addresses:
        - 10.10.10.66-10.10.10.70
        - 10.0.0.60/32
        - 10.0.0.61/32
        - 10.0.0.62/32
        - 10.0.0.65/32

        name: default
        protocol: layer2