apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: myipaddresspool
  namespace: flux-system
spec:
  addresses:
  - 10.10.10.60-10.10.10.70
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: flux-system