---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: intel-gpu-plugin
spec:
  releaseName: intel-gpu-plugin
  interval: 10m0s
  values:
    image:
      tag: 0.23
    nodeSelector:
      feature.node.kubernetes.io/pci-0300_8086.present: "true"
  chart:
    spec:
      chart: intel-gpu-plugin
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system