apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sonarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sonarr
  policy:
    semver:
      range: '>= 3.0.0'
---
# bad versioning
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: calibre-web-automated
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: calibre-web-automated
  policy:
    semver:
      range: '>= 3.0.0'
      #stripPrefix: 'v'
---
# bad versioning
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: calibre-web-automated-book-downloader
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: calibre-web-automated-book-downloader
  #policy:
   # semver:
    #  range: '>= 3.0.0'
      #stripPrefix: 'v'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: mealie
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mealie
  policy:
    semver:
      range: '>= 1.3.2'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: maintainerr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: maintainerr
  policy:
    semver:
      range: '>= 2.0.4'
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: calibre
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: calibre
#   policy:
#     semver:
#       range: '>= 7.7.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: minecraft
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: minecraft
  policy:
    semver:
      range: '>= 2021.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frigate
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frigate
  policy:
    semver:
      range: '>= 0.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pinchflat
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: pinchflat
  policy:
    semver:
      range: '>= 2021.12.0'
---
# Commented out until stable builds are available.
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: readarr
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: readarr
#   policy:
#     semver:
#       range: '>= 7.7.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: radarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radarr
  policy:
    semver:
      range: '>= 3.0.0'
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: ombi
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: ombi
#   policy:
#     semver:
#       range: '>= 4.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: overseerr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: overseerr
  policy:
    semver:
      range: '>= 1.33.1 <1000.0.0'
# ---
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: tautulli
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: tautulli
#   policy:
#     semver:
#       range: '>= 2.13.3 <1000.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sabnzbd
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sabnzbd
  policy:
    semver:
      range: '>= 3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homeassistant
  policy:
    semver:
      range: '>= 2021.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: musicassistant
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: musicassistant
  policy:
    semver:
      range: '>= 2.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: plex
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: plex
  filterTags:
    pattern: '^(?P<major>0|[0-9]\d*)\.(?P<minor>[0-9][0-9])\.(?P<patch>0|[0-9]\d*)\.(?P<something>0|[0-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: unifi
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: unifi
  policy:
    semver:
      range: '>= 5.12.0'
---
# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: double-take
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: double-take
#   policy:
#     semver:
#       range: '>= 1.12.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: eclipse-mosquitto
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: eclipse-mosquitto
  policy:
    semver:
      range: '>= 2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zigbee2mqtt
  policy:
    semver:
      range: '>= 1.26.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: appdaemon
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: appdaemon
  policy:
    semver:
      range: '>= 4.2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wyzebridge
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wyzebridge
  policy:
    semver:
      range: '>= 1.9.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jellyfin
  policy:
    semver:
      range: '>= 8.0.0 <1000.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: qbittorrent
  policy:
    semver:
      range: '>= 5.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: prowlarr
  policy:
    semver:
      range: '>= 1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sftpgo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sftpgo
  policy:
    semver:
      range: '>= 2.5'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: piper
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: piper
  policy:
    semver:
      range: '>= 1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: whisper
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: whisper
  policy:
    semver:
      range: '>= 1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pot-provider
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: pot-provider
  policy:
    semver:
      range: '>= 0.3.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: immich-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-server
  policy:
    semver:
      range: '>= 1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: immich-machine-learning
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-machine-learning
  filterTags:
    pattern: '^v(\d+\.\d+\.\d+)-openvino$'
    extract: '$1'
  policy:
    semver:
      range: '>= 1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: redis
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: redis
  filterTags:
    pattern: '^(\d+\.\d+\.\d+)-alpine$'
    extract: '$1'
  policy:
    semver:
      range: '>= 6.2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: paperless-ngx
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: paperless-ngx
  policy:
    semver:
      range: '>= 2.16.1'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: karakeep
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: karakeep
  policy:
    semver:
      range: '>= 0.24.0'
---