apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: myipaddresspool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.10.60/32
  - 10.10.10.61/32
  - 10.10.10.62/32
  - 10.10.10.63/32
  - 10.10.10.64/32
  - 10.10.10.65/32
  - 10.10.10.66/32
  - 10.10.10.67/32
  - 10.10.10.68/32
  - 10.10.10.69/32
  - 10.10.10.160/32
  - 10.10.10.165/32
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system