apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v3.3.0 # {"$imagepolicy": "flux-system:mealie"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America\Toronto
        - name: MAX_WORKERS
          value: "1"
        - name: WEB_CONCURRENCY
          value: "1"
        - name: BASE_URL
          value: "https://mealie.tallflix.ca"
        - name: OIDC_AUTH_ENABLED
          value: "true"
        - name: OIDC_PROVIDER_NAME
          value: "Authentik"
        - name: OIDC_SIGNUP_ENABLED
          value: "true"
        - name: OIDC_CONFIGURATION_URL
          valueFrom:
            secretKeyRef:
              name: mealie-secrets
              key: OIDC_CONFIGURATION_URL
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mealie-secrets
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mealie-secrets
              key: OIDC_CLIENT_SECRET
        # - name: OIDC_ADMIN_GROUPS
        #   valueFrom:
        #     secretKeyRef:
        #       name: mealie-secrets
        #       key: OIDC_ADMIN_GROUPS
        - name: OIDC_AUTO_REDIRECT
          value: "true"
        - name: OIDC_REMEMBER_ME
          value: "true"
        volumeMounts:
        - name: mealie-config
          mountPath: /app/data/
      volumes:
      - name: mealie-config
        persistentVolumeClaim:
          claimName: mealie-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: default
  labels:
    app: mealie
spec:
  selector:
    app: mealie
  ports:
  - name: mealie
    port: 9000
    targetPort: 9000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "mealie.tallflix.ca"
    secretName: tls-secret-mealie
  rules:
  - host: "mealie.tallflix.ca"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mealie
            port:
              number: 9000
